
/* A lexical scanner generated by flex */

/* Target: C/C++ */
/* START of m4 controls */
/* M4_YY_TABLES_VERIFY = 0 */
/* YY_MAIN = 0 */
/* M4_MODE_NO_DO_STDINIT */
/* M4_MODE_NO_YYTEXT_IS_ARRAY */
/* M4_MODE_NO_YYMORE_USED */
/* M4_MODE_REAL_FULLSPD */
/* M4_MODE_NO_REAL_FULLTBL */
/* M4_MODE_NO_CPP_USE_READ */
/* M4_MODE_NO_VARIABLE_TRAILING_CONTEXT_RULES */
/* M4_MODE_FIND_ACTION_REJECT_REALLY_USED */
/* M4_MODE_NO_USES_REJECT */
/* M4_MODE_FULLSPD */
/* M4_MODE_NO_BOL_NEEDED */
/* M4_MODE_NO_USEECS */
/* M4_MODE_GENTABLES */
/* M4_MODE_NO_INTERACTIVE */
/* M4_MODE_NO_YYWRAP */
/* M4_MODE_C_ONLY */
/* M4_MODE_PREFIX = S1_ */
/* M4_MODE_NO_YYINPUT */
/* M4_YY_NO_TOP_STATE */
/* M4_YY_NO_YYUNPUT */
/* M4_YY_STACK_USED */
/* M4_MODE_NO_REWRITE */
/* END of m4 controls */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define S1__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer S1__create_buffer
#endif

#ifdef yy_delete_buffer
#define S1__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer S1__delete_buffer
#endif

#ifdef yy_scan_buffer
#define S1__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer S1__scan_buffer
#endif

#ifdef yy_scan_string
#define S1__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string S1__scan_string
#endif

#ifdef yy_scan_bytes
#define S1__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes S1__scan_bytes
#endif

#ifdef yy_init_buffer
#define S1__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer S1__init_buffer
#endif

#ifdef yy_flush_buffer
#define S1__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer S1__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define S1__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state S1__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define S1__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer S1__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define S1_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state S1_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define S1_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state S1_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define S1_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack S1_ensure_buffer_stack
#endif

#ifdef yylex
#define S1_lex_ALREADY_DEFINED
#else
#define yylex S1_lex
#endif

#ifdef yyrestart
#define S1_restart_ALREADY_DEFINED
#else
#define yyrestart S1_restart
#endif

#ifdef yylex_init
#define S1_lex_init_ALREADY_DEFINED
#else
#define yylex_init S1_lex_init
#endif

#ifdef yylex_init_extra
#define S1_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra S1_lex_init_extra
#endif

#ifdef yylex_destroy
#define S1_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy S1_lex_destroy
#endif

#ifdef yyget_debug
#define S1_get_debug_ALREADY_DEFINED
#else
#define yyget_debug S1_get_debug
#endif

#ifdef yyset_debug
#define S1_set_debug_ALREADY_DEFINED
#else
#define yyset_debug S1_set_debug
#endif

#ifdef yyget_extra
#define S1_get_extra_ALREADY_DEFINED
#else
#define yyget_extra S1_get_extra
#endif

#ifdef yyset_extra
#define S1_set_extra_ALREADY_DEFINED
#else
#define yyset_extra S1_set_extra
#endif

#ifdef yyget_in
#define S1_get_in_ALREADY_DEFINED
#else
#define yyget_in S1_get_in
#endif

#ifdef yyset_in
#define S1_set_in_ALREADY_DEFINED
#else
#define yyset_in S1_set_in
#endif

#ifdef yyget_out
#define S1_get_out_ALREADY_DEFINED
#else
#define yyget_out S1_get_out
#endif

#ifdef yyset_out
#define S1_set_out_ALREADY_DEFINED
#else
#define yyset_out S1_set_out
#endif

#ifdef yyget_leng
#define S1_get_leng_ALREADY_DEFINED
#else
#define yyget_leng S1_get_leng
#endif

#ifdef yyget_text
#define S1_get_text_ALREADY_DEFINED
#else
#define yyget_text S1_get_text
#endif

#ifdef yyget_lineno
#define S1_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno S1_get_lineno
#endif

#ifdef yyset_lineno
#define S1_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno S1_set_lineno
#endif

#ifdef yywrap
#define S1_wrap_ALREADY_DEFINED
#else
#define yywrap S1_wrap
#endif

#ifdef yyalloc
#define S1_alloc_ALREADY_DEFINED
#else
#define yyalloc S1_alloc
#endif

#ifdef yyrealloc
#define S1_realloc_ALREADY_DEFINED
#else
#define yyrealloc S1_realloc
#endif

#ifdef yyfree
#define S1_free_ALREADY_DEFINED
#else
#define yyfree S1_free
#endif

#ifdef yytext
#define S1_text_ALREADY_DEFINED
#else
#define yytext S1_text
#endif

#ifdef yyleng
#define S1_leng_ALREADY_DEFINED
#else
#define yyleng S1_leng
#endif

#ifdef yyin
#define S1_in_ALREADY_DEFINED
#else
#define yyin S1_in
#endif

#ifdef yyout
#define S1_out_ALREADY_DEFINED
#else
#define yyout S1_out
#endif

#ifdef yyflexdebug
#define S1_flexdebug_ALREADY_DEFINED
#else
#define yyflexdebug S1_flexdebug
#endif

#ifdef yylineno
#define S1_lineno_ALREADY_DEFINED
#else
#define yylineno S1_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */

# if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#  define YYFLEX_USE_STDINT
# endif
# if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#  define YYFLEX_USE_STDINT
# else
#  if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#   define YYFLEX_USE_STDINT
#  endif
# endif
# ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
# else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#  ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#   ifdef __cplusplus
#include <climits>
#   else
#include <limits.h>
#   endif
#   if UINT_MAX >= 4294967295
#    define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#   endif
#  else
typedef char flex_int8_t;
#  endif
#  ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#  endif
# endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define yybegin(s) (yy_start) = 1 + 2 * (s)
/* Legacy interface */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define yystart() (((yy_start) - 1) / 2)
/* Legacy interfaces */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* The state buf must be large enough to hold one state per character in the main buffer,
 * plus the start state, plus the two end-of-buffer byte states.
 */
#define YY_STATE_BUF_EXTRA_SPACE 3
#define YY_STATE_BUF_SIZE   (YY_BUF_SIZE + YY_STATE_BUF_EXTRA_SPACE)

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *yybuffer;
/* Legacy interface */
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define yyunput(c) yyunput_r( c, (yytext_ptr)  )
/* Legacy interface */
#define unput(c) yyunput_r( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyatbol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static yybuffer * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_current_buffer() ( (yy_buffer_stack)			\
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Legacy interface */
#define YY_CURRENT_BUFFER yy_current_buffer()
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( yybuffer new_buffer  );
yybuffer yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( yybuffer b  );
void yy_flush_buffer ( yybuffer b  );
void yypush_buffer_state ( yybuffer new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( yybuffer b, FILE *file  );
#define yy_flush_current_buffer() yy_flush_buffer( yy_current_buffer() )
#define YY_FLUSH_BUFFER yy_flush_current_buffer()

yybuffer yy_scan_buffer ( char *base, yy_size_t size  );
yybuffer yy_scan_string ( const char *yy_str  );
yybuffer yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) { \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
			yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}
#define yysetbol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}
#define yyatbol() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
/* Legacy interface */
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
#define yy_set_bol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}

/* Begin user sect3 */

#define S1_wrap() (/*CONSTCOND*/1)

#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef const struct yy_trans_info *yy_state_type;

extern int yylineno;
int yylineno = 1;

/* Watch out: yytext_ptr is a variable when yytext is an array,
 * but it's a macro when yytext is a pointer.
 */

extern char *yytext;

#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */
/* START of m4 controls */
/* M4_MODE_NO_NULTRANS */
/* M4_MODE_NO_NULTRANS_FULLTBL */
/* M4_MODE_NULTRANS_FULLSPD */
/* END of m4 controls */

/* START of Flex-generated definitions */
#define YY_NUM_RULES 28
#define YY_END_OF_BUFFER 29
#define YY_JAMBASE 0
#define YY_JAMSTATE 0
#define YY_NUL_EC 128
#define YY_OFFSET_TYPE flex_int32_t
/* END of Flex-generated definitions */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yypanic ( const char* msg  );

struct yy_trans_info
	{
	/* We require that yy_verify and yy_nxt must be of the same size int. */

	YY_OFFSET_TYPE yy_verify;

	/* In cases where its sister yy_verify *is* a "yes, there is
	 * a transition", yy_nxt is the offset (in records) to the
	 * next state.  In most cases where there is no transition,
	 * the value of yy_nxt is irrelevant.  If yy_nxt is the -1th
	 * record of a state, though, then yy_nxt is the action number
	 * for that state.
	 */
	 YY_OFFSET_TYPE yy_nxt;

	};

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	do { \
	(yytext_ptr) = yy_bp; \
	 \
	yyleng = (int) (yy_cp - yy_bp); \
	 \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
 \
	(yy_c_buf_p) = yy_cp; \
	} while(0)

extern int yyflexdebug;
int yyflexdebug = 0;
/* Legacy interface */
#ifndef yy_flex_debug
#define yy_flex_debug yyflexdebug
#endif

/* %% [2.0] data tables for the DFA are inserted here */

/* footprint: 22608 bytes */

/* m4 controls begin */
/* M4_MODE_HAS_BACKING_UP */
/* M4_MODE_NEED_YY_CP */
/* M4_MODE_NULTRANS_WRAP */
/* m4 controls end */

/* The transition table */
static const struct yy_trans_info yy_transition[2821] = {
{   0,   0},
{   0,2693},
{   0,   0},
{   0,2691},
{   1, 520},

{   2, 520},
{   3, 520},
{   4, 520},
{   5, 520},
{   6, 520},

{   7, 520},
{   8, 520},
{   9, 522},
{  10, 524},
{  11, 520},

{  12, 520},
{  13, 520},
{  14, 520},
{  15, 520},
{  16, 520},

{  17, 520},
{  18, 520},
{  19, 520},
{  20, 520},
{  21, 520},

{  22, 520},
{  23, 520},
{  24, 520},
{  25, 520},
{  26, 520},

{  27, 520},
{  28, 520},
{  29, 520},
{  30, 520},
{  31, 520},

{  32, 522},
{  33, 520},
{  34, 520},
{  35, 520},
{  36, 526},

{  37, 520},
{  38, 520},
{  39, 520},
{  40, 528},
{  41, 530},

{  42, 533},
{  43, 536},
{  44, 538},
{  45, 536},
{  46, 548},

{  47, 550},
{  48, 553},
{  49, 613},
{  50, 613},
{  51, 613},

{  52, 613},
{  53, 613},
{  54, 613},
{  55, 613},
{  56, 613},

{  57, 613},
{  58, 556},
{  59, 558},
{  60, 564},
{  61, 520},

{  62, 566},
{  63, 520},
{  64, 520},
{  65, 672},
{  66, 672},

{  67, 672},
{  68, 672},
{  69, 672},
{  70, 672},
{  71, 717},

{  72, 717},
{  73, 717},
{  74, 717},
{  75, 717},
{  76, 717},

{  77, 717},
{  78, 717},
{  79, 717},
{  80, 717},
{  81, 717},

{  82, 717},
{  83, 717},
{  84, 717},
{  85, 717},
{  86, 717},

{  87, 717},
{  88, 717},
{  89, 717},
{  90, 717},
{  91, 520},

{  92, 776},
{  93, 580},
{  94, 600},
{  95, 635},
{  96, 520},

{  97, 814},
{  98, 814},
{  99, 814},
{ 100, 814},
{ 101, 814},

{ 102, 814},
{ 103, 840},
{ 104, 840},
{ 105, 840},
{ 106, 840},

{ 107, 840},
{ 108, 840},
{ 109, 840},
{ 110, 840},
{ 111, 840},

{ 112, 840},
{ 113, 840},
{ 114, 840},
{ 115, 840},
{ 116, 840},

{ 117, 840},
{ 118, 840},
{ 119, 840},
{ 120, 840},
{ 121, 840},

{ 122, 840},
{ 123, 640},
{ 124, 642},
{ 125, 686},
{ 126, 520},

{ 127, 520},
{ 128, 520},
{   0,   0},
{   0,2561},
{   1, 390},

{   2, 390},
{   3, 390},
{   4, 390},
{   5, 390},
{   6, 390},

{   7, 390},
{   8, 390},
{   9, 392},
{  10, 394},
{  11, 390},

{  12, 390},
{  13, 390},
{  14, 390},
{  15, 390},
{  16, 390},

{  17, 390},
{  18, 390},
{  19, 390},
{  20, 390},
{  21, 390},

{  22, 390},
{  23, 390},
{  24, 390},
{  25, 390},
{  26, 390},

{  27, 390},
{  28, 390},
{  29, 390},
{  30, 390},
{  31, 390},

{  32, 392},
{  33, 390},
{  34, 390},
{  35, 390},
{  36, 396},

{  37, 390},
{  38, 390},
{  39, 390},
{  40, 398},
{  41, 400},

{  42, 403},
{  43, 406},
{  44, 408},
{  45, 406},
{  46, 418},

{  47, 420},
{  48, 423},
{  49, 483},
{  50, 483},
{  51, 483},

{  52, 483},
{  53, 483},
{  54, 483},
{  55, 483},
{  56, 483},

{  57, 483},
{  58, 426},
{  59, 428},
{  60, 434},
{  61, 390},

{  62, 436},
{  63, 390},
{  64, 390},
{  65, 542},
{  66, 542},

{  67, 542},
{  68, 542},
{  69, 542},
{  70, 542},
{  71, 587},

{  72, 587},
{  73, 587},
{  74, 587},
{  75, 587},
{  76, 587},

{  77, 587},
{  78, 587},
{  79, 587},
{  80, 587},
{  81, 587},

{  82, 587},
{  83, 587},
{  84, 587},
{  85, 587},
{  86, 587},

{  87, 587},
{  88, 587},
{  89, 587},
{  90, 587},
{  91, 390},

{  92, 646},
{  93, 450},
{  94, 470},
{  95, 505},
{  96, 390},

{  97, 684},
{  98, 684},
{  99, 684},
{ 100, 684},
{ 101, 684},

{ 102, 684},
{ 103, 710},
{ 104, 710},
{ 105, 710},
{ 106, 710},

{ 107, 710},
{ 108, 710},
{ 109, 710},
{ 110, 710},
{ 111, 710},

{ 112, 710},
{ 113, 710},
{ 114, 710},
{ 115, 710},
{ 116, 710},

{ 117, 710},
{ 118, 710},
{ 119, 710},
{ 120, 710},
{ 121, 710},

{ 122, 710},
{ 123, 510},
{ 124, 512},
{ 125, 556},
{ 126, 390},

{ 127, 390},
{ 128, 390},
{   0,   0},
{   0,2431},
{   1, 428},

{   2, 428},
{   3, 428},
{   4, 428},
{   5, 428},
{   6, 428},

{   7, 428},
{   8, 428},
{   9, 428},
{  10, 428},
{  11, 428},

{  12, 428},
{  13, 428},
{  14, 428},
{  15, 428},
{  16, 428},

{  17, 428},
{  18, 428},
{  19, 428},
{  20, 428},
{  21, 428},

{  22, 428},
{  23, 428},
{  24, 428},
{  25, 428},
{  26, 428},

{  27, 428},
{  28, 428},
{  29, 428},
{  30, 428},
{  31, 428},

{  32, 428},
{  33, 428},
{  34, 428},
{  35, 428},
{  36, 428},

{  37, 428},
{  38, 428},
{  39, 428},
{  40, 428},
{  41, 428},

{  42, 428},
{  43, 428},
{  44, 428},
{  45, 428},
{  46, 428},

{  47, 428},
{  48, 428},
{  49, 428},
{  50, 428},
{  51, 428},

{  52, 428},
{  53, 428},
{  54, 428},
{  55, 428},
{  56, 428},

{  57, 428},
{  58, 428},
{  59, 428},
{  60, 428},
{  61, 428},

{  62, 428},
{  63, 428},
{  64, 428},
{  65, 428},
{  66, 428},

{  67, 428},
{  68, 428},
{  69, 428},
{  70, 428},
{  71, 428},

{  72, 428},
{  73, 428},
{  74, 428},
{  75, 428},
{  76, 428},

{  77, 428},
{  78, 428},
{  79, 428},
{  80, 428},
{  81, 428},

{  82, 428},
{  83, 428},
{  84, 428},
{  85, 428},
{  86, 428},

{  87, 428},
{  88, 428},
{  89, 428},
{  90, 428},
{  91, 428},

{  92, 428},
{  93, 428},
{  94, 428},
{  95, 428},
{  96, 428},

{  97, 428},
{  98, 428},
{  99, 428},
{ 100, 428},
{ 101, 428},

{ 102, 428},
{ 103, 428},
{ 104, 428},
{ 105, 428},
{ 106, 428},

{ 107, 428},
{ 108, 428},
{ 109, 428},
{ 110, 428},
{ 111, 428},

{ 112, 428},
{ 113, 428},
{ 114, 428},
{ 115, 428},
{ 116, 428},

{ 117, 428},
{ 118, 428},
{ 119, 428},
{ 120, 428},
{ 121, 428},

{ 122, 428},
{ 123, 428},
{ 124, 428},
{ 125, 428},
{ 126, 428},

{ 127, 428},
{ 128, 428},
{   0,   0},
{   0,2301},
{   1, 298},

{   2, 298},
{   3, 298},
{   4, 298},
{   5, 298},
{   6, 298},

{   7, 298},
{   8, 298},
{   9, 298},
{  10, 298},
{  11, 298},

{  12, 298},
{  13, 298},
{  14, 298},
{  15, 298},
{  16, 298},

{  17, 298},
{  18, 298},
{  19, 298},
{  20, 298},
{  21, 298},

{  22, 298},
{  23, 298},
{  24, 298},
{  25, 298},
{  26, 298},

{  27, 298},
{  28, 298},
{  29, 298},
{  30, 298},
{  31, 298},

{  32, 298},
{  33, 298},
{  34, 298},
{  35, 298},
{  36, 298},

{  37, 298},
{  38, 298},
{  39, 298},
{  40, 298},
{  41, 298},

{  42, 298},
{  43, 298},
{  44, 298},
{  45, 298},
{  46, 298},

{  47, 298},
{  48, 298},
{  49, 298},
{  50, 298},
{  51, 298},

{  52, 298},
{  53, 298},
{  54, 298},
{  55, 298},
{  56, 298},

{  57, 298},
{  58, 298},
{  59, 298},
{  60, 298},
{  61, 298},

{  62, 298},
{  63, 298},
{  64, 298},
{  65, 298},
{  66, 298},

{  67, 298},
{  68, 298},
{  69, 298},
{  70, 298},
{  71, 298},

{  72, 298},
{  73, 298},
{  74, 298},
{  75, 298},
{  76, 298},

{  77, 298},
{  78, 298},
{  79, 298},
{  80, 298},
{  81, 298},

{  82, 298},
{  83, 298},
{  84, 298},
{  85, 298},
{  86, 298},

{  87, 298},
{  88, 298},
{  89, 298},
{  90, 298},
{  91, 298},

{  92, 298},
{  93, 298},
{  94, 298},
{  95, 298},
{  96, 298},

{  97, 298},
{  98, 298},
{  99, 298},
{ 100, 298},
{ 101, 298},

{ 102, 298},
{ 103, 298},
{ 104, 298},
{ 105, 298},
{ 106, 298},

{ 107, 298},
{ 108, 298},
{ 109, 298},
{ 110, 298},
{ 111, 298},

{ 112, 298},
{ 113, 298},
{ 114, 298},
{ 115, 298},
{ 116, 298},

{ 117, 298},
{ 118, 298},
{ 119, 298},
{ 120, 298},
{ 121, 298},

{ 122, 298},
{ 123, 298},
{ 124, 298},
{ 125, 298},
{ 126, 298},

{ 127, 298},
{ 128, 298},
{   0,  27},
{   0,2171},
{   0,  24},

{   0,2169},
{   0,  15},
{   0,2167},
{   0,   5},
{   0,2165},

{   0,  13},
{   0,2163},
{   0,  19},
{   0,2161},
{   9, 177},

{   0,  21},
{   0,2158},
{  10, 244},
{   0,  27},
{   0,2155},

{   0,   2},
{   0,2153},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   6},
{   0,2143},
{   0,  25},
{   0,2141},
{   0,   0},

{   0,   4},
{   0,2138},
{  32, 177},
{   0,   1},
{   0,2135},

{   0,  20},
{   0,2133},
{   0,   0},
{   0,   0},
{   0,   0},

{  36, 254},
{   0,  14},
{   0,2127},
{   0,   8},
{   0,2125},

{   0,   0},
{  40, 281},
{   0,   0},
{   0,   0},
{  41, 288},

{   0,   0},
{   0,   0},
{   0,   0},
{  42, 297},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  11},
{   0,2111},
{   0,   0},

{  44, 294},
{   0,   0},
{  48, 310},
{  49, 428},
{  50, 428},

{  51, 428},
{  52, 428},
{  53, 428},
{  54, 428},
{  55, 428},

{  56, 428},
{  57, 428},
{  46, 294},
{   0,   0},
{  43, 421},

{  47, 307},
{  45, 421},
{   0,  17},
{   0,2091},
{  48, 436},

{  49, 496},
{  50, 496},
{  51, 496},
{  52, 496},
{  53, 496},

{  54, 496},
{  55, 496},
{  56, 496},
{  57, 496},
{   0,   0},

{   0,   4},
{   0,2078},
{  58, 351},
{   0,   0},
{   0,   0},

{  59, 351},
{  65, 519},
{  66, 519},
{  67, 519},
{  68, 519},

{  69, 519},
{  70, 519},
{  60, 412},
{   0,   0},
{   0,   0},

{   0,   0},
{  62, 419},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  22},
{   0,2056},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  10},
{   0,2051},
{   0,  16},

{   0,2049},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  97, 519},
{  98, 519},

{  99, 519},
{ 100, 519},
{ 101, 519},
{ 102, 519},
{  43, 361},

{   0,   0},
{  45, 361},
{   0,   0},
{   0,   0},
{  48, 497},

{  49, 569},
{  50, 569},
{  51, 569},
{  52, 569},
{  53, 569},

{  54, 569},
{  55, 569},
{  56, 569},
{  57, 569},
{   0,  23},

{   0,2019},
{  93, 411},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  65, 459},
{  66, 459},
{  67, 459},
{  68, 459},

{  69, 459},
{  70, 459},
{   0,   0},
{   0,  18},
{   0,2005},

{   0,  28},
{   0,2003},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  94, 399},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,  24},
{   0,1992},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   9,   0},
{   0,   0},
{  97, 459},
{  98, 459},

{  99, 459},
{ 100, 459},
{ 101, 459},
{ 102, 459},
{   0,  23},

{   0,1974},
{   0,   0},
{   0,   0},
{  48, 400},
{  49, 400},

{  50, 400},
{  51, 400},
{  52, 400},
{  53, 400},
{  54, 400},

{  55, 400},
{  56, 400},
{  57, 400},
{  95, 366},
{  32,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  65, 548},
{  66, 548},
{  67, 548},
{  68, 548},
{  69, 548},

{  70, 548},
{  71, 586},
{  72, 586},
{  73, 586},
{  74, 586},

{  75, 586},
{  76, 586},
{  77, 586},
{  78, 586},
{  79, 586},

{  80, 586},
{  81, 586},
{  82, 586},
{  83, 586},
{  84, 586},

{  85, 586},
{  86, 586},
{  87, 586},
{  88, 586},
{  89, 586},

{  90, 586},
{ 123, 371},
{   0,   0},
{   0,   0},
{ 124, 419},

{   0,  15},
{   0,1923},
{  97, 400},
{  98, 400},
{  99, 400},

{ 100, 400},
{ 101, 400},
{ 102, 400},
{   0,  27},
{   0,1915},

{   0,   0},
{  10,   0},
{   0,   5},
{   0,1911},
{   0,   0},

{  65, 541},
{  66, 541},
{  67, 541},
{  68, 541},
{  69, 541},

{  70, 541},
{  71, 541},
{  72, 541},
{  73, 541},
{  74, 541},

{  75, 541},
{  76, 541},
{  77, 541},
{  78, 541},
{  79, 541},

{  80, 541},
{  81, 541},
{  82, 541},
{  83, 541},
{  84, 541},

{  85, 541},
{  86, 541},
{  87, 541},
{  88, 541},
{  89, 541},

{  90, 541},
{   0,  13},
{   0,1882},
{  34, 211},
{ 125, 377},

{   0,   0},
{   0,  12},
{   0,1877},
{  39, 211},
{  36,   0},

{   0,  19},
{   0,1873},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  21},
{   0,1861},
{   0,   2},

{   0,1859},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  12},
{   0,1851},
{   0,   6},

{   0,1849},
{   0,   0},
{   0,   0},
{   0,   9},
{   0,1845},

{   0,   0},
{   0,   0},
{  40,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,  25},

{   0,1834},
{   0,   0},
{  41,   0},
{   0,   0},
{   0,   0},

{  48, 258},
{  49, 258},
{  50, 258},
{  51, 258},
{  52, 258},

{  53, 258},
{  54, 258},
{  55, 258},
{  56, 258},
{  57, 258},

{  42,   0},
{   0,   0},
{  98, 211},
{   0,   0},
{  44,   0},

{   0,   0},
{ 102, 211},
{  65, 258},
{  66, 258},
{  67, 258},

{  68, 258},
{  69, 258},
{  70, 258},
{   0,   0},
{ 110, 211},

{   0,   0},
{  46,   0},
{  43, 128},
{ 114, 211},
{  45, 128},

{ 116, 211},
{   0,   0},
{  48,   0},
{  49, 118},
{  50, 118},

{  51, 118},
{  52, 118},
{  53, 118},
{  54, 118},
{  55, 118},

{  56, 118},
{  57, 118},
{  47, 676},
{   0,   0},
{   0,   1},

{   0,1784},
{   0,  20},
{   0,1782},
{   0,   0},
{  97, 498},

{  98, 498},
{  99, 498},
{ 100, 498},
{ 101, 498},
{ 102, 498},

{ 103, 536},
{ 104, 536},
{ 105, 536},
{ 106, 536},
{ 107, 536},

{ 108, 536},
{ 109, 536},
{ 110, 536},
{ 111, 536},
{ 112, 536},

{ 113, 536},
{ 114, 536},
{ 115, 536},
{ 116, 536},
{ 117, 536},

{ 118, 536},
{ 119, 536},
{ 120, 536},
{ 121, 536},
{ 122, 536},

{  97, 510},
{  98, 510},
{  99, 510},
{ 100, 510},
{ 101, 510},

{ 102, 510},
{ 103, 510},
{ 104, 510},
{ 105, 510},
{ 106, 510},

{ 107, 510},
{ 108, 510},
{ 109, 510},
{ 110, 510},
{ 111, 510},

{ 112, 510},
{ 113, 510},
{ 114, 510},
{ 115, 510},
{ 116, 510},

{ 117, 510},
{ 118, 510},
{ 119, 510},
{ 120, 510},
{ 121, 510},

{ 122, 510},
{   0,   9},
{   0,1727},
{  58,   0},
{   0,   0},

{   0,   0},
{  59,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,1717},
{   0,  14},
{   0,1715},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   8},
{   0,1706},
{   0,   7},

{   0,1704},
{   0,   4},
{   0,1702},
{   0,  11},
{   0,1700},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,  17},
{   0,1692},
{   0,  22},
{   0,1690},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  43,  10},
{   0,   0},
{  45,  10},
{   0,  10},
{   0,1680},

{  48, 472},
{  49, 510},
{  50, 510},
{  51, 510},
{  52, 510},

{  53, 510},
{  54, 510},
{  55, 510},
{  56, 510},
{  57, 510},

{  48,-128},
{  49, -10},
{  50, -10},
{  51, -10},
{  52, -10},

{  53, -10},
{  54, -10},
{  55, -10},
{  56, -10},
{  57, -10},

{  43, -15},
{   0,   0},
{  45, -15},
{   0,   0},
{  60,   0},

{  48,   0},
{  49,  60},
{  50,  60},
{  51,  60},
{  52,  60},

{  53,  60},
{  54,  60},
{  55,  60},
{  56,  60},
{  57,  60},

{  62,   0},
{   0,   4},
{   0,1642},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  65,  83},
{  66,  83},
{  67,  83},

{  68,  83},
{  69,  83},
{  70,  83},
{   0,  16},
{   0,1630},

{   0,  18},
{   0,1628},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,  26},

{   0,1619},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  92, 676},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  93,   0},
{   0,   0},
{  97,  83},

{  98,  83},
{  99,  83},
{ 100,  83},
{ 101,  83},
{ 102,  83},

{  43, -75},
{  94,   0},
{  45, -75},
{   0,   0},
{  95,   0},

{  48,  61},
{  49, 133},
{  50, 133},
{  51, 133},
{  52, 133},

{  53, 133},
{  54, 133},
{  55, 133},
{  56, 133},
{  57, 133},

{   0,   0},
{   0,   0},
{   0,   4},
{   0,1581},
{   0,   0},

{   0,   0},
{   0,   0},
{  65,  23},
{  66,  23},
{  67,  23},

{  68,  23},
{  69,  23},
{  70,  23},
{  48,   0},
{  49,   0},

{  50,   0},
{  51,   0},
{  52,   0},
{  53,   0},
{  54,   0},

{  55,   0},
{  56,   0},
{  57,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{ 123,   0},
{   0,   0},
{   0,   0},

{  65,   0},
{  66,   0},
{  67,   0},
{  68,   0},
{  69,   0},

{  70,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  97,  23},

{  98,  23},
{  99,  23},
{ 100,  23},
{ 101,  23},
{ 102,  23},

{   0,   0},
{  43,-136},
{   0,   0},
{  45,-136},
{   0,   0},

{   0,   0},
{  48,   0},
{  49,  72},
{  50,  72},
{  51,  72},

{  52,  72},
{  53,  72},
{  54,  72},
{  55,  72},
{  56,  72},

{  57,  72},
{   0,   0},
{  97,   0},
{  98,   0},
{  99,   0},

{ 100,   0},
{ 101,   0},
{ 102,   0},
{  65, -38},
{  66, -38},

{  67, -38},
{  68, -38},
{  69, -38},
{  70, -38},
{   0,   4},

{   0,1509},
{   0,   0},
{   0,   0},
{ 124,   0},
{   0,   0},

{   0,   0},
{ 125,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  97, -38},
{  98, -38},
{  99, -38},
{ 100, -38},
{ 101, -38},

{ 102, -38},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,  23},
{   0,1471},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  43,-208},
{   0,   0},

{  45,-208},
{   0,   0},
{   0,   0},
{  48, -72},
{  49,   0},

{  50,   0},
{  51,   0},
{  52,   0},
{  53,   0},
{  54,   0},

{  55,   0},
{  56,   0},
{  57,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  65,-110},
{  66,-110},
{  67,-110},
{  68,-110},
{  69,-110},

{  70,-110},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,  23},
{   0,1433},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  48,-148},
{  49,-148},
{  50,-148},
{  51,-148},

{  52,-148},
{  53,-148},
{  54,-148},
{  55,-148},
{  56,-148},

{  57,-148},
{   0,   0},
{  97,-110},
{  98,-110},
{  99,-110},

{ 100,-110},
{ 101,-110},
{ 102,-110},
{  65,   0},
{  66,   0},

{  67,   0},
{  68,   0},
{  69,   0},
{  70,   0},
{  71,  38},

{  72,  38},
{  73,  38},
{  74,  38},
{  75,  38},
{  76,  38},

{  77,  38},
{  78,  38},
{  79,  38},
{  80,  38},
{  81,  38},

{  82,  38},
{  83,  38},
{  84,  38},
{  85,  38},
{  86,  38},

{  87,  38},
{  88,  38},
{  89,  38},
{  90,  38},
{   0,  12},

{   0,1379},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  97,-148},
{  98,-148},
{  99,-148},
{ 100,-148},
{ 101,-148},

{ 102,-148},
{  65,   0},
{  66,   0},
{  67,   0},
{  68,   0},

{  69,   0},
{  70,   0},
{  71,   0},
{  72,   0},
{  73,   0},

{  74,   0},
{  75,   0},
{  76,   0},
{  77,   0},
{  78,   0},

{  79,   0},
{  80,   0},
{  81,   0},
{  82,   0},
{  83,   0},

{  84,   0},
{  85,   0},
{  86,   0},
{  87,   0},
{  88,   0},

{  89,   0},
{  90,   0},
{   0,  12},
{   0,1341},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  48,-240},
{  49,-240},

{  50,-240},
{  51,-240},
{  52,-240},
{  53,-240},
{  54,-240},

{  55,-240},
{  56,-240},
{  57,-240},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  65,-240},
{  66,-240},
{  67,-240},
{  68,-240},
{  69,-240},

{  70,-240},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  97,   0},
{  98,   0},
{  99,   0},

{ 100,   0},
{ 101,   0},
{ 102,   0},
{ 103,  38},
{ 104,  38},

{ 105,  38},
{ 106,  38},
{ 107,  38},
{ 108,  38},
{ 109,  38},

{ 110,  38},
{ 111,  38},
{ 112,  38},
{ 113,  38},
{ 114,  38},

{ 115,  38},
{ 116,  38},
{ 117,  38},
{ 118,  38},
{ 119,  38},

{ 120,  38},
{ 121,  38},
{ 122,  38},
{   0,   9},
{   0,1255},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  97,   0},
{  98,   0},
{  99,   0},
{ 100,   0},
{ 101,   0},

{ 102,   0},
{ 103,   0},
{ 104,   0},
{ 105,   0},
{ 106,   0},

{ 107,   0},
{ 108,   0},
{ 109,   0},
{ 110,   0},
{ 111,   0},

{ 112,   0},
{ 113,   0},
{ 114,   0},
{ 115,   0},
{ 116,   0},

{ 117,   0},
{ 118,   0},
{ 119,   0},
{ 120,   0},
{ 121,   0},

{ 122,   0},
{   0,   9},
{   0,1217},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  43,-462},
{   0,   0},
{  45,-462},

{   0,   0},
{   0,   0},
{  48,   0},
{  49,  38},
{  50,  38},

{  51,  38},
{  52,  38},
{  53,  38},
{  54,  38},
{  55,  38},

{  56,  38},
{  57,  38},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  43,-500},
{   0,   0},
{  45,-500},
{   0,   0},
{   0,   0},

{  48, -38},
{  49,   0},
{  50,   0},
{  51,   0},
{  52,   0},

{  53,   0},
{  54,   0},
{  55,   0},
{  56,   0},
{  57,   0},

{   0,   3},
{   0,1158},
{   1, 248},
{   2, 248},
{   3, 248},

{   4, 248},
{   5, 248},
{   6, 248},
{   7, 248},
{   8, 248},

{   9, 248},
{   0,   0},
{  11, 248},
{  12, 248},
{  13, 248},

{  14, 248},
{  15, 248},
{  16, 248},
{  17, 248},
{  18, 248},

{  19, 248},
{  20, 248},
{  21, 248},
{  22, 248},
{  23, 248},

{  24, 248},
{  25, 248},
{  26, 248},
{  27, 248},
{  28, 248},

{  29, 248},
{  30, 248},
{  31, 248},
{  32, 248},
{  33, 248},

{  34, 248},
{  35, 248},
{  36, 248},
{  37, 248},
{  38, 248},

{  39, 248},
{  40, 248},
{  41, 248},
{  42, 248},
{  43, 248},

{  44, 248},
{  45, 248},
{  46, 248},
{  47, 378},
{  48, 248},

{  49, 248},
{  50, 248},
{  51, 248},
{  52, 248},
{  53, 248},

{  54, 248},
{  55, 248},
{  56, 248},
{  57, 248},
{  58, 248},

{  59, 248},
{  60, 248},
{  61, 248},
{  62, 248},
{  63, 248},

{  64, 248},
{  65, 248},
{  66, 248},
{  67, 248},
{  68, 248},

{  69, 248},
{  70, 248},
{  71, 248},
{  72, 248},
{  73, 248},

{  74, 248},
{  75, 248},
{  76, 248},
{  77, 248},
{  78, 248},

{  79, 248},
{  80, 248},
{  81, 248},
{  82, 248},
{  83, 248},

{  84, 248},
{  85, 248},
{  86, 248},
{  87, 248},
{  88, 248},

{  89, 248},
{  90, 248},
{  91, 248},
{  92, 248},
{  93, 248},

{  94, 248},
{  95, 248},
{  96, 248},
{  97, 248},
{  98, 248},

{  99, 248},
{ 100, 248},
{ 101, 248},
{ 102, 248},
{ 103, 248},

{ 104, 248},
{ 105, 248},
{ 106, 248},
{ 107, 248},
{ 108, 248},

{ 109, 248},
{ 110, 248},
{ 111, 248},
{ 112, 248},
{ 113, 248},

{ 114, 248},
{ 115, 248},
{ 116, 248},
{ 117, 248},
{ 118, 248},

{ 119, 248},
{ 120, 248},
{ 121, 248},
{ 122, 248},
{ 123, 248},

{ 124, 248},
{ 125, 248},
{ 126, 248},
{ 127, 248},
{ 128, 248},

{   0,   0},
{   0,1028},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  34,-676},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  39,-676},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  98,-676},

{   0,   0},
{   0,   0},
{   0,   0},
{ 102,-676},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{ 110,-676},
{   0,   0},
{   0,   0},
{   0,   0},

{ 114,-676},
{   0,   0},
{ 116,-676},
{   0,   3},
{   0, 910},

{   1,   0},
{   2,   0},
{   3,   0},
{   4,   0},
{   5,   0},

{   6,   0},
{   7,   0},
{   8,   0},
{   9,   0},
{   0,   0},

{  11,   0},
{  12,   0},
{  13,   0},
{  14,   0},
{  15,   0},

{  16,   0},
{  17,   0},
{  18,   0},
{  19,   0},
{  20,   0},

{  21,   0},
{  22,   0},
{  23,   0},
{  24,   0},
{  25,   0},

{  26,   0},
{  27,   0},
{  28,   0},
{  29,   0},
{  30,   0},

{  31,   0},
{  32,   0},
{  33,   0},
{  34,   0},
{  35,   0},

{  36,   0},
{  37,   0},
{  38,   0},
{  39,   0},
{  40,   0},

{  41,   0},
{  42,   0},
{  43,   0},
{  44,   0},
{  45,   0},

{  46,   0},
{  47, 260},
{  48,   0},
{  49,   0},
{  50,   0},

{  51,   0},
{  52,   0},
{  53,   0},
{  54,   0},
{  55,   0},

{  56,   0},
{  57,   0},
{  58,   0},
{  59,   0},
{  60,   0},

{  61,   0},
{  62,   0},
{  63,   0},
{  64,   0},
{  65,   0},

{  66,   0},
{  67,   0},
{  68,   0},
{  69,   0},
{  70,   0},

{  71,   0},
{  72,   0},
{  73,   0},
{  74,   0},
{  75,   0},

{  76,   0},
{  77,   0},
{  78,   0},
{  79,   0},
{  80,   0},

{  81,   0},
{  82,   0},
{  83,   0},
{  84,   0},
{  85,   0},

{  86,   0},
{  87,   0},
{  88,   0},
{  89,   0},
{  90,   0},

{  91,   0},
{  92,   0},
{  93,   0},
{  94,   0},
{  95,   0},

{  96,   0},
{  97,   0},
{  98,   0},
{  99,   0},
{ 100,   0},

{ 101,   0},
{ 102,   0},
{ 103,   0},
{ 104,   0},
{ 105,   0},

{ 106,   0},
{ 107,   0},
{ 108,   0},
{ 109,   0},
{ 110,   0},

{ 111,   0},
{ 112,   0},
{ 113,   0},
{ 114,   0},
{ 115,   0},

{ 116,   0},
{ 117,   0},
{ 118,   0},
{ 119,   0},
{ 120,   0},

{ 121,   0},
{ 122,   0},
{ 123,   0},
{ 124,   0},
{ 125,   0},

{ 126,   0},
{ 127,   0},
{ 128,   0},
{   0,   3},
{   0, 780},

{   1,-130},
{   2,-130},
{   3,-130},
{   4,-130},
{   5,-130},

{   6,-130},
{   7,-130},
{   8,-130},
{   9,-130},
{   0,   0},

{  11,-130},
{  12,-130},
{  13,-130},
{  14,-130},
{  15,-130},

{  16,-130},
{  17,-130},
{  18,-130},
{  19,-130},
{  20,-130},

{  21,-130},
{  22,-130},
{  23,-130},
{  24,-130},
{  25,-130},

{  26,-130},
{  27,-130},
{  28,-130},
{  29,-130},
{  30,-130},

{  31,-130},
{  32,-130},
{  33,-130},
{  34,-130},
{  35,-130},

{  36,-130},
{  37,-130},
{  38,-130},
{  39,-130},
{  40,-130},

{  41,-130},
{  42,-130},
{  43,-130},
{  44,-130},
{  45,-130},

{  46,-130},
{  47, 260},
{  48,-130},
{  49,-130},
{  50,-130},

{  51,-130},
{  52,-130},
{  53,-130},
{  54,-130},
{  55,-130},

{  56,-130},
{  57,-130},
{  58,-130},
{  59,-130},
{  60,-130},

{  61,-130},
{  62,-130},
{  63,-130},
{  64,-130},
{  65,-130},

{  66,-130},
{  67,-130},
{  68,-130},
{  69,-130},
{  70,-130},

{  71,-130},
{  72,-130},
{  73,-130},
{  74,-130},
{  75,-130},

{  76,-130},
{  77,-130},
{  78,-130},
{  79,-130},
{  80,-130},

{  81,-130},
{  82,-130},
{  83,-130},
{  84,-130},
{  85,-130},

{  86,-130},
{  87,-130},
{  88,-130},
{  89,-130},
{  90,-130},

{  91,-130},
{  92,-130},
{  93,-130},
{  94,-130},
{  95,-130},

{  96,-130},
{  97,-130},
{  98,-130},
{  99,-130},
{ 100,-130},

{ 101,-130},
{ 102,-130},
{ 103,-130},
{ 104,-130},
{ 105,-130},

{ 106,-130},
{ 107,-130},
{ 108,-130},
{ 109,-130},
{ 110,-130},

{ 111,-130},
{ 112,-130},
{ 113,-130},
{ 114,-130},
{ 115,-130},

{ 116,-130},
{ 117,-130},
{ 118,-130},
{ 119,-130},
{ 120,-130},

{ 121,-130},
{ 122,-130},
{ 123,-130},
{ 124,-130},
{ 125,-130},

{ 126,-130},
{ 127,-130},
{ 128,-130},
{   0,   3},
{   0, 650},

{   1,-260},
{   2,-260},
{   3,-260},
{   4,-260},
{   5,-260},

{   6,-260},
{   7,-260},
{   8,-260},
{   9,-260},
{   0,   0},

{  11,-260},
{  12,-260},
{  13,-260},
{  14,-260},
{  15,-260},

{  16,-260},
{  17,-260},
{  18,-260},
{  19,-260},
{  20,-260},

{  21,-260},
{  22,-260},
{  23,-260},
{  24,-260},
{  25,-260},

{  26,-260},
{  27,-260},
{  28,-260},
{  29,-260},
{  30,-260},

{  31,-260},
{  32,-260},
{  33,-260},
{  34,-260},
{  35,-260},

{  36,-260},
{  37,-260},
{  38,-260},
{  39,-260},
{  40,-260},

{  41,-260},
{  42,-260},
{  43,-260},
{  44,-260},
{  45,-260},

{  46,-260},
{  47, 260},
{  48,-260},
{  49,-260},
{  50,-260},

{  51,-260},
{  52,-260},
{  53,-260},
{  54,-260},
{  55,-260},

{  56,-260},
{  57,-260},
{  58,-260},
{  59,-260},
{  60,-260},

{  61,-260},
{  62,-260},
{  63,-260},
{  64,-260},
{  65,-260},

{  66,-260},
{  67,-260},
{  68,-260},
{  69,-260},
{  70,-260},

{  71,-260},
{  72,-260},
{  73,-260},
{  74,-260},
{  75,-260},

{  76,-260},
{  77,-260},
{  78,-260},
{  79,-260},
{  80,-260},

{  81,-260},
{  82,-260},
{  83,-260},
{  84,-260},
{  85,-260},

{  86,-260},
{  87,-260},
{  88,-260},
{  89,-260},
{  90,-260},

{  91,-260},
{  92,-260},
{  93,-260},
{  94,-260},
{  95,-260},

{  96,-260},
{  97,-260},
{  98,-260},
{  99,-260},
{ 100,-260},

{ 101,-260},
{ 102,-260},
{ 103,-260},
{ 104,-260},
{ 105,-260},

{ 106,-260},
{ 107,-260},
{ 108,-260},
{ 109,-260},
{ 110,-260},

{ 111,-260},
{ 112,-260},
{ 113,-260},
{ 114,-260},
{ 115,-260},

{ 116,-260},
{ 117,-260},
{ 118,-260},
{ 119,-260},
{ 120,-260},

{ 121,-260},
{ 122,-260},
{ 123,-260},
{ 124,-260},
{ 125,-260},

{ 126,-260},
{ 127,-260},
{ 128,-260},
{   0,   3},
{   0, 520},

{   1,-390},
{   2,-390},
{   3,-390},
{   4,-390},
{   5,-390},

{   6,-390},
{   7,-390},
{   8,-390},
{   9,-390},
{   0,   0},

{  11,-390},
{  12,-390},
{  13,-390},
{  14,-390},
{  15,-390},

{  16,-390},
{  17,-390},
{  18,-390},
{  19,-390},
{  20,-390},

{  21,-390},
{  22,-390},
{  23,-390},
{  24,-390},
{  25,-390},

{  26,-390},
{  27,-390},
{  28,-390},
{  29,-390},
{  30,-390},

{  31,-390},
{  32,-390},
{  33,-390},
{  34,-390},
{  35,-390},

{  36,-390},
{  37,-390},
{  38,-390},
{  39,-390},
{  40,-390},

{  41,-390},
{  42,-390},
{  43,-390},
{  44,-390},
{  45,-390},

{  46,-390},
{  47, 260},
{  48,-390},
{  49,-390},
{  50,-390},

{  51,-390},
{  52,-390},
{  53,-390},
{  54,-390},
{  55,-390},

{  56,-390},
{  57,-390},
{  58,-390},
{  59,-390},
{  60,-390},

{  61,-390},
{  62,-390},
{  63,-390},
{  64,-390},
{  65,-390},

{  66,-390},
{  67,-390},
{  68,-390},
{  69,-390},
{  70,-390},

{  71,-390},
{  72,-390},
{  73,-390},
{  74,-390},
{  75,-390},

{  76,-390},
{  77,-390},
{  78,-390},
{  79,-390},
{  80,-390},

{  81,-390},
{  82,-390},
{  83,-390},
{  84,-390},
{  85,-390},

{  86,-390},
{  87,-390},
{  88,-390},
{  89,-390},
{  90,-390},

{  91,-390},
{  92,-390},
{  93,-390},
{  94,-390},
{  95,-390},

{  96,-390},
{  97,-390},
{  98,-390},
{  99,-390},
{ 100,-390},

{ 101,-390},
{ 102,-390},
{ 103,-390},
{ 104,-390},
{ 105,-390},

{ 106,-390},
{ 107,-390},
{ 108,-390},
{ 109,-390},
{ 110,-390},

{ 111,-390},
{ 112,-390},
{ 113,-390},
{ 114,-390},
{ 115,-390},

{ 116,-390},
{ 117,-390},
{ 118,-390},
{ 119,-390},
{ 120,-390},

{ 121,-390},
{ 122,-390},
{ 123,-390},
{ 124,-390},
{ 125,-390},

{ 126,-390},
{ 127,-390},
{ 128,-390},
{   0,   3},
{   0, 390},

{   1,-520},
{   2,-520},
{   3,-520},
{   4,-520},
{   5,-520},

{   6,-520},
{   7,-520},
{   8,-520},
{   9,-520},
{   0,   0},

{  11,-520},
{  12,-520},
{  13,-520},
{  14,-520},
{  15,-520},

{  16,-520},
{  17,-520},
{  18,-520},
{  19,-520},
{  20,-520},

{  21,-520},
{  22,-520},
{  23,-520},
{  24,-520},
{  25,-520},

{  26,-520},
{  27,-520},
{  28,-520},
{  29,-520},
{  30,-520},

{  31,-520},
{  32,-520},
{  33,-520},
{  34,-520},
{  35,-520},

{  36,-520},
{  37,-520},
{  38,-520},
{  39,-520},
{  40,-520},

{  41,-520},
{  42,-520},
{  43,-520},
{  44,-520},
{  45,-520},

{  46,-520},
{  47, 260},
{  48,-520},
{  49,-520},
{  50,-520},

{  51,-520},
{  52,-520},
{  53,-520},
{  54,-520},
{  55,-520},

{  56,-520},
{  57,-520},
{  58,-520},
{  59,-520},
{  60,-520},

{  61,-520},
{  62,-520},
{  63,-520},
{  64,-520},
{  65,-520},

{  66,-520},
{  67,-520},
{  68,-520},
{  69,-520},
{  70,-520},

{  71,-520},
{  72,-520},
{  73,-520},
{  74,-520},
{  75,-520},

{  76,-520},
{  77,-520},
{  78,-520},
{  79,-520},
{  80,-520},

{  81,-520},
{  82,-520},
{  83,-520},
{  84,-520},
{  85,-520},

{  86,-520},
{  87,-520},
{  88,-520},
{  89,-520},
{  90,-520},

{  91,-520},
{  92,-520},
{  93,-520},
{  94,-520},
{  95,-520},

{  96,-520},
{  97,-520},
{  98,-520},
{  99,-520},
{ 100,-520},

{ 101,-520},
{ 102,-520},
{ 103,-520},
{ 104,-520},
{ 105,-520},

{ 106,-520},
{ 107,-520},
{ 108,-520},
{ 109,-520},
{ 110,-520},

{ 111,-520},
{ 112,-520},
{ 113,-520},
{ 114,-520},
{ 115,-520},

{ 116,-520},
{ 117,-520},
{ 118,-520},
{ 119,-520},
{ 120,-520},

{ 121,-520},
{ 122,-520},
{ 123,-520},
{ 124,-520},
{ 125,-520},

{ 126,-520},
{ 127,-520},
{ 128,-520},
{   0,   3},
{   0, 260},

{   1,-650},
{   2,-650},
{   3,-650},
{   4,-650},
{   5,-650},

{   6,-650},
{   7,-650},
{   8,-650},
{   9,-650},
{   0,   0},

{  11,-650},
{  12,-650},
{  13,-650},
{  14,-650},
{  15,-650},

{  16,-650},
{  17,-650},
{  18,-650},
{  19,-650},
{  20,-650},

{  21,-650},
{  22,-650},
{  23,-650},
{  24,-650},
{  25,-650},

{  26,-650},
{  27,-650},
{  28,-650},
{  29,-650},
{  30,-650},

{  31,-650},
{  32,-650},
{  33,-650},
{  34,-650},
{  35,-650},

{  36,-650},
{  37,-650},
{  38,-650},
{  39,-650},
{  40,-650},

{  41,-650},
{  42,-650},
{  43,-650},
{  44,-650},
{  45,-650},

{  46,-650},
{  47,   0},
{  48,-650},
{  49,-650},
{  50,-650},

{  51,-650},
{  52,-650},
{  53,-650},
{  54,-650},
{  55,-650},

{  56,-650},
{  57,-650},
{  58,-650},
{  59,-650},
{  60,-650},

{  61,-650},
{  62,-650},
{  63,-650},
{  64,-650},
{  65,-650},

{  66,-650},
{  67,-650},
{  68,-650},
{  69,-650},
{  70,-650},

{  71,-650},
{  72,-650},
{  73,-650},
{  74,-650},
{  75,-650},

{  76,-650},
{  77,-650},
{  78,-650},
{  79,-650},
{  80,-650},

{  81,-650},
{  82,-650},
{  83,-650},
{  84,-650},
{  85,-650},

{  86,-650},
{  87,-650},
{  88,-650},
{  89,-650},
{  90,-650},

{  91,-650},
{  92,-650},
{  93,-650},
{  94,-650},
{  95,-650},

{  96,-650},
{  97,-650},
{  98,-650},
{  99,-650},
{ 100,-650},

{ 101,-650},
{ 102,-650},
{ 103,-650},
{ 104,-650},
{ 105,-650},

{ 106,-650},
{ 107,-650},
{ 108,-650},
{ 109,-650},
{ 110,-650},

{ 111,-650},
{ 112,-650},
{ 113,-650},
{ 114,-650},
{ 115,-650},

{ 116,-650},
{ 117,-650},
{ 118,-650},
{ 119,-650},
{ 120,-650},

{ 121,-650},
{ 122,-650},
{ 123,-650},
{ 124,-650},
{ 125,-650},

{ 126,-650},
{ 127,-650},
{ 128,-650},
{   0,   3},
{   0, 130},

{   1,-780},
{   2,-780},
{   3,-780},
{   4,-780},
{   5,-780},

{   6,-780},
{   7,-780},
{   8,-780},
{   9,-780},
{   0,   0},

{  11,-780},
{  12,-780},
{  13,-780},
{  14,-780},
{  15,-780},

{  16,-780},
{  17,-780},
{  18,-780},
{  19,-780},
{  20,-780},

{  21,-780},
{  22,-780},
{  23,-780},
{  24,-780},
{  25,-780},

{  26,-780},
{  27,-780},
{  28,-780},
{  29,-780},
{  30,-780},

{  31,-780},
{  32,-780},
{  33,-780},
{  34,-780},
{  35,-780},

{  36,-780},
{  37,-780},
{  38,-780},
{  39,-780},
{  40,-780},

{  41,-780},
{  42,-780},
{  43,-780},
{  44,-780},
{  45,-780},

{  46,-780},
{  47,   0},
{  48,-780},
{  49,-780},
{  50,-780},

{  51,-780},
{  52,-780},
{  53,-780},
{  54,-780},
{  55,-780},

{  56,-780},
{  57,-780},
{  58,-780},
{  59,-780},
{  60,-780},

{  61,-780},
{  62,-780},
{  63,-780},
{  64,-780},
{  65,-780},

{  66,-780},
{  67,-780},
{  68,-780},
{  69,-780},
{  70,-780},

{  71,-780},
{  72,-780},
{  73,-780},
{  74,-780},
{  75,-780},

{  76,-780},
{  77,-780},
{  78,-780},
{  79,-780},
{  80,-780},

{  81,-780},
{  82,-780},
{  83,-780},
{  84,-780},
{  85,-780},

{  86,-780},
{  87,-780},
{  88,-780},
{  89,-780},
{  90,-780},

{  91,-780},
{  92,-780},
{  93,-780},
{  94,-780},
{  95,-780},

{  96,-780},
{  97,-780},
{  98,-780},
{  99,-780},
{ 100,-780},

{ 101,-780},
{ 102,-780},
{ 103,-780},
{ 104,-780},
{ 105,-780},

{ 106,-780},
{ 107,-780},
{ 108,-780},
{ 109,-780},
{ 110,-780},

{ 111,-780},
{ 112,-780},
{ 113,-780},
{ 114,-780},
{ 115,-780},

{ 116,-780},
{ 117,-780},
{ 118,-780},
{ 119,-780},
{ 120,-780},

{ 121,-780},
{ 122,-780},
{ 123,-780},
{ 124,-780},
{ 125,-780},

{ 126,-780},
{ 127,-780},
{ 128,-780},
{ 129,  29},
{   1,   0},

};

/* Table of pointers to start states. */
static const struct yy_trans_info *yy_start_state_list[5] = {
	&yy_transition[1],
	&yy_transition[3],
	&yy_transition[133],
	&yy_transition[263],
	&yy_transition[393],
};

/* Definitions for backing up.  We don't need them if yyreject()
 * is being used because then we use an alternative backing-up
 * technique instead.
 */
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of yyreject() which flex missed.
 */
#define yyreject() reject_used_but_not_detected
#define REJECT reject_used_but_not_detected

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

char *yytext;

/* %% [3.0] static declarations conditional on mode switches go here */
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "globals.h"
int line_start;
int line_stop;
int debug;
char line_buffer[2048];
struct PRINT {
	char * name;
	bool   print_match;	
}data[]={
	//false will show the RLE for the match
	//true  will show the actual match 
	"COLON",false,
	"COMMA",false,
	"COMMENT",false,
	"DIGIT",false,
	"DOLLAR",false,
	"DOT",false,
	"ESCAPESEQUENCE",false,
	"FSLASH",false,
	"GT",false,
	"INTEGER",false,
	"LBRACE",false,
	"LBRACK",false,
	"LOWER",false,
	"LPAREN",false,
	"LT",false,
	"MONTH",false,
	"NL",false,
	"OR",false,
	"POWER",false,
	"RBRACE",false,
	"RBRACK",false,
	"RPAREN",false,
	"SEMICOLON",false,
	"STAR",false,
	"TIMEZONE",false,
	"UNDERSCORE",false,
	"UPPER",false,
	"WS",false,
	"XDIGIT",false,
};

bool search_print_struct(char* state){
	for(int i=0;i<sizeof(data)/sizeof(data[0]);i++){
		if(strcmp(state,data[i].name)==0){
			return data[i].print_match;
		}
	}
}
#line 4021 "lex.S1_.c"

#line 4023 "lex.S1_.c"

#define INITIAL 0
#define line 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_YYUNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#define YY_NO_YYINPUT 1

#ifndef YY_NO_YYINPUT

static int yyinput ( void );
#ifndef __cplusplus
#define input yyinput
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
/*
 * Amount of stuff to slurp up with each read.
 * We assume the stdio library has already
 * chosen a fit size foe whatever platform
 * we're running on.
 */
#define YY_READ_BUF_SIZE BUFSIZ

/* Size of default input buffer. We want to be able to fit two
 * OS-level reads, but efficiency gains as the buffer size
 * increases fall off after that
 */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE	(2 * YY_READ_BUF_SIZE)
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef yyecho

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define yyecho() do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)

#endif
/* Legacy interface */
#define ECHO yyecho()

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yypanic (const char* msg ) {
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Report a fatal error. Legacy interface. */
#ifndef YY_FATAL_ERROR

#define YY_FATAL_ERROR(msg) yypanic( msg )

#endif

/* Legacy interface */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) do {result = yyread(buf, max_size );} while (0)

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */

static int yyread(char *buf, size_t max_size ) {

	int result;
	
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) {
		int c = '*';
		int n;
		for ( n = 0; n < max_size &&
			      (c = getc( yyin )) != EOF && c != '\n'; ++n ) {
			buf[n] = (char) c;
		}
		if ( c == '\n' ) {
			buf[n++] = (char) c;
		}
		if ( c == EOF && ferror( yyin ) ) {
			YY_FATAL_ERROR( "input in flex scanner failed" );
		}
		result = n;
	} else {
		errno=0;
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) {
			if( errno != EINTR) {
				YY_FATAL_ERROR( "input in flex scanner failed" );
				break;
			}
			errno=0;
			clearerr(yyin);
		}
	}

	 return result;
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)

#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#define YY_RULE_SETUP \
		YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) ) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) ) {
			(yy_start) = 1;	/* first start state */
		}
		if ( ! yyin ) {

			yyin = stdin;

		}
		if ( ! yyout ) {

			yyout = stdout;

		}
		if ( yy_current_buffer() == NULL ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
	}

	/* open scope of user declarationns */
	{
/* %% [4.0] user's declarations go here */
#line 102 "scanner.l"



#line 4278 "lex.S1_.c"

		while ( /*CONSTCOND*/1 ) {		/* loops until end-of-file is reached */

			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	yy_match:
			/* Generate the code to find the next match. */

		{
			const struct yy_trans_info *yy_trans_info;
			YY_CHAR yy_c;

			for ( yy_c = YY_SC_TO_UI(*yy_cp);
			      (yy_trans_info = &yy_current_state[yy_c])->yy_verify == yy_c;
			      yy_c = YY_SC_TO_UI(*++yy_cp) )
			{
				yy_current_state += yy_trans_info->yy_nxt;

		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

			}
		}

	yy_find_action:
			/* code to find the action number goes here */
			yy_act = yy_current_state[-1].yy_nxt;
			
			YY_DO_BEFORE_ACTION;

		do_action:	/* This label is used only to access EOF actions. */

			switch ( yy_act ) { /* beginning of action switch */

			case 0: /* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);

				/* Backing-up info for compressed tables is taken \after/ */
				/* yy_cp has been incremented for the next state. */
				yy_cp = (yy_last_accepting_cpos);
				yy_cp++;
				
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

/* %% [5.0] user actions get inserted here */
	case 1:
YY_RULE_SETUP

#line 105 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("COLON")){
			printf("%s",yytext);	
        } else { 
			printf("{COLON}");
		}
	} else {
		if(search_print_struct("COLON")){
			printf("%s",yytext);	
		} else {	
			printf("{COLON}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 2:
YY_RULE_SETUP

#line 123 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("COMMA")){
			printf("%s",yytext);	
        } else { 
			printf("{COMMA}");
		}
	} else {
		if(search_print_struct("COMMA")){
			printf("%s",yytext);	
		} else {	
			printf("{COMMA}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 3:
YY_RULE_SETUP

#line 141 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("COMMENT")){
			printf("%s",yytext);	
        } else { 
			printf("{COMMENT}");
		}
	} else {
		if(search_print_struct("COMMENT")){
			printf("%s",yytext);	
		} else {	
			printf("{COMMENT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 4:
YY_RULE_SETUP

#line 160 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("DIGIT")){
			printf("%s",yytext);	
        } else { 
			printf("{DIGIT}");
		}
	} else {
		if(search_print_struct("DIGIT")){
			printf("%s",yytext);	
		} else {	
			printf("{DIGIT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 5:
YY_RULE_SETUP

#line 178 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("DOLLAR")){
			printf("%s",yytext);	
        } else { 
			printf("{DOLLAR}");
		}
	} else {
		if(search_print_struct("DOLLAR")){
			printf("%s",yytext);	
		} else {	
			printf("{DOLLAR}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 6:
YY_RULE_SETUP

#line 196 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("DOT")){
			printf("%s",yytext);	
        } else { 
			printf("{DOT}");
		}
	} else {
		if(search_print_struct("DOT")){
			printf("%s",yytext);	
		} else {	
			printf("{DOT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 7:
YY_RULE_SETUP

#line 214 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("ESCAPESEQUENCE")){
			printf("%s",yytext);	
        } else { 
			printf("{ESCAPESEQUENCE}");
		}
	} else {
		if(search_print_struct("ESCAPESEQUENCE")){
			printf("%s",yytext);	
		} else {	
			printf("{ESCAPESEQUENCE}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 8:
YY_RULE_SETUP

#line 234 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("GT")){
			printf("%s",yytext);	
        } else { 
			printf("{GT}");
		}
	} else {
		if(search_print_struct("GT")){
			printf("%s",yytext);	
		} else {	
			printf("{GT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 9:
YY_RULE_SETUP

#line 253 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("INTEGER")){
			printf("%s",yytext);	
        } else { 
			printf("{INTEGER}");
		}
	} else {
		if(search_print_struct("INTEGER")){
			printf("%s",yytext);	
		} else {	
			printf("{INTEGER}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 10:
YY_RULE_SETUP

#line 271 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("LBRACE")){
			printf("%s",yytext);	
        } else { 
			printf("{LBRACE}");
		}
	} else {
		if(search_print_struct("LBRACE")){
			printf("%s",yytext);	
		} else {	
			printf("{LBRACE}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 11:
YY_RULE_SETUP

#line 289 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("LT")){
			printf("%s",yytext);	
        } else { 
			printf("{LBRACK}");
		}
	} else {
		if(search_print_struct("LT")){
			printf("%s",yytext);	
		} else {	
			printf("{LBRACK}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 12:
YY_RULE_SETUP

#line 307 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("LOWER")){
			printf("%s",yytext);	
        } else { 
			printf("{LOWER}");
		}
	} else {
		if(search_print_struct("LOWER")){
			printf("%s",yytext);	
		} else {	
			printf("{LOWER}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 13:
YY_RULE_SETUP

#line 325 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("LPAREN")){
			printf("%s",yytext);	
        } else { 
			printf("{LPAREN}");
		}
	} else {
		if(search_print_struct("LPAREN")){
			printf("%s",yytext);	
		} else {	
			printf("{LPAREN}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 14:
YY_RULE_SETUP

#line 343 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("WORD")){
			printf("%s",yytext);	
        } else { 
			printf("{LT}");
		}
	} else {
		if(search_print_struct("WORD")){
			printf("%s",yytext);	
		} else {	
			printf("{LT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 15:
/* rule 15 can match eol */
YY_RULE_SETUP

#line 363 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("NL")){
			printf("%s",yytext);	
        } else { 
			printf("{NL}\n");
		}
	} else {
		if(search_print_struct("NL")){
			printf("%s",yytext);	
		} else {	
			printf("{NL}{%d}\n",yyleng);
		}
	}
	if(strlen(line_buffer)>0){
		printf("%s\n\n",line_buffer);
	}
	memset(line_buffer,'\0',2048);
}
	/*LINTED*/break;
	case 16:
YY_RULE_SETUP

#line 385 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("OR")){
			printf("%s",yytext);	
        } else { 
			printf("{OR}");
		}
	} else {
		if(search_print_struct("OR")){
			printf("%s",yytext);	
		} else {	
			printf("{OR}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 17:
YY_RULE_SETUP

#line 403 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("POWER")){
			printf("%s",yytext);	
        } else { 
			printf("{POWER}");
		}
	} else {
		if(search_print_struct("POWER")){
			printf("%s",yytext);	
		} else {	
			printf("{POWER}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 18:
YY_RULE_SETUP

#line 422 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("RBRACE")){
			printf("%s",yytext);	
        } else { 
			printf("{RBRACE}");
		}
	} else {
		if(search_print_struct("RBRACE")){
			printf("%s",yytext);	
		} else {	
			printf("{RBRACE}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 19:
YY_RULE_SETUP

#line 442 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("RPAREN")){
			printf("%s",yytext);	
        } else { 
			printf("{RPAREN}");
		}
	} else {
		if(search_print_struct("RPAREN")){
			printf("%s",yytext);	
		} else {	
			printf("{RPAREN}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 20:
YY_RULE_SETUP

#line 460 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("SEMICOLON")){
			printf("%s",yytext);	
        } else { 
			printf("{SEMICOLON}");
		}
	} else {
		if(search_print_struct("SEMICOLON")){
			printf("%s",yytext);	
		} else {	
			printf("{SEMICOLON}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 21:
YY_RULE_SETUP

#line 480 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("STAR")){
			printf("%s",yytext);	
        } else { 
			printf("{STAR}");
		}
	} else {
		if(search_print_struct("STAR")){
			printf("%s",yytext);	
		} else {	
			printf("{STAR}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 22:
YY_RULE_SETUP

#line 500 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("UNDERSCORE")){
			printf("%s",yytext);	
        } else { 
			printf("{UNDERSCORE}");
		}
	} else {
		if(search_print_struct("UNDERSCORE")){
			printf("%s",yytext);	
		} else {	
			printf("{UNDERSCORE}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 23:
YY_RULE_SETUP

#line 518 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("UPPER")){
			printf("%s",yytext);	
        } else { 
			printf("{UPPER}");
		}
	} else {
		if(search_print_struct("UPPER")){
			printf("%s",yytext);	
		} else {	
			printf("{UPPER}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 24:
YY_RULE_SETUP

#line 536 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("WS")){
			printf("%s",yytext);	
        } else { 
			printf("{WS}");
		}
	} else {
		if(search_print_struct("WS")){
			printf("%s",yytext);	
		} else {	
			printf("{WS}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 25:
YY_RULE_SETUP

#line 553 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("FSLASH")){
			printf("%s",yytext);	
        } else { 
			printf("{FSLASH}");
		}
	} else {
		if(search_print_struct("FSLASH")){
			printf("%s",yytext);	
		} else {	
			printf("{FSLASH}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 26:
YY_RULE_SETUP

#line 570 "scanner.l"
{
	strcat(line_buffer,yytext);
	if(yyleng==1){
		if(search_print_struct("XDIGIT")){
			printf("%s",yytext);	
        } else { 
			printf("{XDIGIT}");
		}
	} else {
		if(search_print_struct("")){
			printf("%s",yytext);	
		} else {	
			printf("{XDIGIT}{%d}",yyleng);
		}
	}
}
	/*LINTED*/break;
	case 27:
YY_RULE_SETUP

#line 589 "scanner.l"
;
	/*LINTED*/break;
	case 28:
YY_RULE_SETUP

#line 590 "scanner.l"
yyecho();
	/*LINTED*/break;
#line 4906 "lex.S1_.c"
#line 4907 "lex.S1_.c"
	case YY_STATE_EOF(INITIAL):
		/* FALLTHROUGH */
	case YY_STATE_EOF(line):
		/* FALLTHROUGH */
		yyterminate();

			case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

				if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
					/* We're scanning a new file or input source.  It's
					 * possible that this happened because the user
					 * just pointed yyin at a new source and called
					 * yylex().  If so, then we have to assure
					 * consistency between yy_current_buffer() and our
					 * globals.  Here is the right place to do so, because
					 * this is the first action (other than possibly a
					 * back-up) that will match for the new input source.
					 */
					(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;

					YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;

					YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
				}

				/* Note that here we test for yy_c_buf_p "<=" to the position
				 * of the first EOB in the buffer, since yy_c_buf_p will
				 * already have been incremented past the NUL character
				 * (since all states make transitions on EOB to the
				 * end-of-buffer state).  Contrast this with the test
				 * in input().
				 */
				if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) { /* This was really a NUL. */
					yy_state_type yy_next_state;

					(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

					yy_current_state = yy_get_previous_state(  );

					/* Okay, we're now positioned to make the NUL
					 * transition.  We couldn't have
					 * yy_get_previous_state() go ahead and do it
					 * for us because it doesn't know how to deal
					 * with the possibility of jamming (and we don't
					 * want to build jamming into it because then it
					 * will run more slowly).
					 */

					yy_next_state = yy_try_NUL_trans( yy_current_state );

					yy_bp = (yytext_ptr) + YY_MORE_ADJ;

					if ( yy_next_state ) {
						/* Consume the NUL. */
						yy_cp = ++(yy_c_buf_p);
						yy_current_state = yy_next_state;
						goto yy_match;
					} else {
						yy_cp = (yy_c_buf_p);
						
						goto yy_find_action;
					}
				} else {	/* not a NUL */
					switch ( yy_get_next_buffer(  ) ) {
					case EOB_ACT_END_OF_FILE:
						(yy_did_buffer_switch_on_eof) = 0;

						if ( yywrap(  ) ) {
							/* Note: because we've taken care in
							 * yy_get_next_buffer() to have set up
							 * yytext, we can now set up
							 * yy_c_buf_p so that if some total
							 * hoser (like flex itself) wants to
							 * call the scanner after we return the
							 * YY_NULL, it'll still work - another
							 * YY_NULL will get returned.
							 */
							(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

							yy_act = YY_STATE_EOF(yystart());
							goto do_action;
						} else {
							if ( ! (yy_did_buffer_switch_on_eof) ) {
								YY_NEW_FILE;
							}
						}
						break;
					case EOB_ACT_CONTINUE_SCAN:
						(yy_c_buf_p) =
							(yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_match;

					case EOB_ACT_LAST_MATCH:
						(yy_c_buf_p) =
						&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_find_action;
					} /* end EOB inner switch */
				} /* end if */
				break;
			} /* case YY_END_OF_BUFFER */
			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
			} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer (void)

{
		char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] ) {
		YY_FATAL_ERROR( "fatal flex scanner internal error--end of buffer missed" );
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
		/* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		} else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i ) {
		*(dest++) = *(source++);
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING ) {
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
	} else {
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 ) { /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			yybuffer b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer ) {
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 ) {
					b->yy_buf_size += b->yy_buf_size / 8;
				} else {
					b->yy_buf_size *= 2;
				}
				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
			} else {
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;
			}
			if ( ! b->yy_ch_buf ) {
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );
			}
			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

		}

		if ( num_to_read > YY_READ_BUF_SIZE ) {
			num_to_read = YY_READ_BUF_SIZE;
		}
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 ) {
		if ( number_to_move == YY_MORE_ADJ ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
		} else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	} else {
		ret_val = EOB_ACT_CONTINUE_SCAN;
	}
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		}
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)

{
	yy_state_type yy_current_state;
	char *yy_cp;
	
	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
		/* Generate the code to find the next state. */
		
		yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : YY_NUL_EC)].yy_nxt;
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )

{
	int yy_is_jam;
		/* Generate code for handling NUL's, if needed. */

	/* First, deal with backing up and setting up yy_cp if the scanner
	 * finds that it should JAM on the NUL.
	 *
	 * Only generate a definition for "yy_cp" if we'll generate code
	 * that uses it.  Otherwise lint and the like complain.
	 */
	char *yy_cp = (yy_c_buf_p);

	int yy_c = YY_NUL_EC;

	const struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	/* If we've entered an accepting state, back up; note that
	 * compressed tables have *already* done such backing up, so
	 * we needn't bother with it again.
	 */
	if ( ! yy_is_jam ) {
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_YYINPUT
int yyinput (void)

{
	int c;
	
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
		} else {
			/* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) ) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart( yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				if ( yywrap(  ) ) {
					return 0;
				}
				if ( ! (yy_did_buffer_switch_on_eof) ) {
					YY_NEW_FILE;
				}
				return yyinput();

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

#endif	/* ifndef YY_NO_YYINPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */

void yyrestart  (FILE * input_file )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	if ( yy_current_buffer() == NULL ) {
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
	        	yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER_LVALUE, input_file );
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */

void yy_switch_to_buffer  (yybuffer  new_buffer )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack ();
	if ( yy_current_buffer() == new_buffer ) {
		return;
	}
	if ( yy_current_buffer() ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)

{
		(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;

	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;

	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */

yybuffer yy_create_buffer  (FILE * file, int  size )

{
	yybuffer b;
	
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if (  b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( b->yy_ch_buf == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */

void yy_delete_buffer (yybuffer  b )

{
	
	if ( b == NULL ) {
		return;
	}
	if ( b == yy_current_buffer() ) {	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (yybuffer) 0;
	}
	if ( b->yy_is_our_buffer ) {
		yyfree( (void *) b->yy_ch_buf  );
	}
	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */

static void yy_init_buffer  (yybuffer  b, FILE * file )

{
	int oerrno = errno;
	
	yy_flush_buffer( b );

	b->yy_input_file = file;

    /* b->yy_input_file should never by NULL but we'll handle it cleanly
	 * on the off chance.
	 */
	if (b->yy_input_file == NULL){
	  b->yy_fill_buffer = 0;
	} else {
	  b->yy_fill_buffer = 1;
	}

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != yy_current_buffer()) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_current_buffer().
 * 
 */

void yy_flush_buffer (yybuffer  b )

{
		if ( b == NULL ) {
		return;
	}
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yyatbol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer() ) {
		yy_load_buffer_state(  );
	}
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */

void yypush_buffer_state (yybuffer new_buffer )

{
		if (new_buffer == NULL) {
		return;
	}
	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( yy_current_buffer() != NULL ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_current_buffer()) {
		(yy_buffer_stack_top)++;
	}
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */

void yypop_buffer_state (void)

{
		if (yy_current_buffer() == NULL) {
		return;
	}
	yy_delete_buffer(yy_current_buffer() );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0) {
		--(yy_buffer_stack_top);
	}
	if (yy_current_buffer() != NULL) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */

static void yyensure_buffer_stack (void)

{
	yy_size_t num_to_alloc;
	
	if ((yy_buffer_stack) == NULL) {
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( (yy_buffer_stack == NULL) ) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {
		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ((yy_buffer_stack) == NULL) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_buffer  (char * base, yy_size_t  size )
{
	yybuffer b;
	
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR ) {
		/* They forgot to leave room for the EOB's. */
		return NULL;
	}
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
	}
	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yyatbol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
yybuffer yy_scan_string (const char * yystr )
{
	
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_bytes  (const char * yybytes, int  _yybytes_len ) {
	yybuffer b;
	char *buf;
	yy_size_t n;
	int i;
	
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( buf == 0 ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
	}
	for ( i = 0; i < _yybytes_len; ++i ) {
		buf[i] = yybytes[i];
	}
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
	}
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

static void yy_push_state (int  _new_state )

{
		if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) ) {
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) ) {
			(yy_start_stack) = (int *) yyalloc( new_size  );

		} else {
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );
		}
		if ( ! (yy_start_stack) ) {
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}
	}
	(yy_start_stack)[(yy_start_stack_ptr)++] = yystart();

	yybegin(_new_state);
}

static void yy_pop_state  (void)

{
		if ( --(yy_start_stack_ptr) < 0 ) {
		YY_FATAL_ERROR( "start-condition stack underflow" );
	}
	yybegin((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do { \
		/* Undo effects of setting up yytext. */ \
		int yyless_macro_arg = (n); \
		YY_LESS_LINENO(yyless_macro_arg);\
			yytext[yyleng] = (yy_hold_char); \
			(yy_c_buf_p) = yytext + yyless_macro_arg; \
			(yy_hold_char) = *(yy_c_buf_p); \
			*(yy_c_buf_p) = '\0'; \
			yyleng = yyless_macro_arg; \
	} while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void) {
	
	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void) {
		return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void) {
		return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void) {
		return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void) {
		return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number ) {
	
	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str ) {
		yyin = _in_str ;
}

void yyset_out (FILE *  _out_str ) {
		yyout = _out_str ;
}

int yyget_debug  (void) {
		return yyflexdebug;
}

void yyset_debug (int  _bdebug ) {
		yyflexdebug = _bdebug ;
}

static int yy_init_globals (void) {
		/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

	(yy_start_stack_ptr) = 0;
	(yy_start_stack_depth) = 0;
	(yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {
	
	/* Pop the buffer stack, destroying each element. */
	while(yy_current_buffer()) {
		yy_delete_buffer( yy_current_buffer()  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	/* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n ) {
		
	int i;
	for ( i = 0; i < n; ++i ) {
		s1[i] = s2[i];
	}
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size ) {
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size ) {
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr ) {
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#line 590 "scanner.l"



    

