
/* A lexical scanner generated by flex */

/* Target: C/C++ */
/* START of m4 controls */
/* M4_YY_TABLES_VERIFY = 0 */
/* YY_MAIN = 0 */
/* M4_MODE_NO_DO_STDINIT */
/* M4_MODE_NO_YYTEXT_IS_ARRAY */
/* M4_MODE_NO_YYMORE_USED */
/* M4_MODE_REAL_FULLSPD */
/* M4_MODE_NO_REAL_FULLTBL */
/* M4_MODE_NO_CPP_USE_READ */
/* M4_MODE_NO_VARIABLE_TRAILING_CONTEXT_RULES */
/* M4_MODE_FIND_ACTION_REJECT_REALLY_USED */
/* M4_MODE_NO_USES_REJECT */
/* M4_MODE_FULLSPD */
/* M4_MODE_NO_BOL_NEEDED */
/* M4_MODE_NO_USEECS */
/* M4_MODE_GENTABLES */
/* M4_MODE_NO_INTERACTIVE */
/* M4_MODE_NO_YYWRAP */
/* M4_MODE_C_ONLY */
/* M4_MODE_PREFIX = S1_ */
/* M4_MODE_NO_YYINPUT */
/* M4_YY_NO_TOP_STATE */
/* M4_YY_NO_YYUNPUT */
/* M4_YY_STACK_USED */
/* M4_MODE_NO_REWRITE */
/* END of m4 controls */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define S1__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer S1__create_buffer
#endif

#ifdef yy_delete_buffer
#define S1__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer S1__delete_buffer
#endif

#ifdef yy_scan_buffer
#define S1__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer S1__scan_buffer
#endif

#ifdef yy_scan_string
#define S1__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string S1__scan_string
#endif

#ifdef yy_scan_bytes
#define S1__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes S1__scan_bytes
#endif

#ifdef yy_init_buffer
#define S1__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer S1__init_buffer
#endif

#ifdef yy_flush_buffer
#define S1__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer S1__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define S1__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state S1__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define S1__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer S1__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define S1_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state S1_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define S1_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state S1_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define S1_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack S1_ensure_buffer_stack
#endif

#ifdef yylex
#define S1_lex_ALREADY_DEFINED
#else
#define yylex S1_lex
#endif

#ifdef yyrestart
#define S1_restart_ALREADY_DEFINED
#else
#define yyrestart S1_restart
#endif

#ifdef yylex_init
#define S1_lex_init_ALREADY_DEFINED
#else
#define yylex_init S1_lex_init
#endif

#ifdef yylex_init_extra
#define S1_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra S1_lex_init_extra
#endif

#ifdef yylex_destroy
#define S1_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy S1_lex_destroy
#endif

#ifdef yyget_debug
#define S1_get_debug_ALREADY_DEFINED
#else
#define yyget_debug S1_get_debug
#endif

#ifdef yyset_debug
#define S1_set_debug_ALREADY_DEFINED
#else
#define yyset_debug S1_set_debug
#endif

#ifdef yyget_extra
#define S1_get_extra_ALREADY_DEFINED
#else
#define yyget_extra S1_get_extra
#endif

#ifdef yyset_extra
#define S1_set_extra_ALREADY_DEFINED
#else
#define yyset_extra S1_set_extra
#endif

#ifdef yyget_in
#define S1_get_in_ALREADY_DEFINED
#else
#define yyget_in S1_get_in
#endif

#ifdef yyset_in
#define S1_set_in_ALREADY_DEFINED
#else
#define yyset_in S1_set_in
#endif

#ifdef yyget_out
#define S1_get_out_ALREADY_DEFINED
#else
#define yyget_out S1_get_out
#endif

#ifdef yyset_out
#define S1_set_out_ALREADY_DEFINED
#else
#define yyset_out S1_set_out
#endif

#ifdef yyget_leng
#define S1_get_leng_ALREADY_DEFINED
#else
#define yyget_leng S1_get_leng
#endif

#ifdef yyget_text
#define S1_get_text_ALREADY_DEFINED
#else
#define yyget_text S1_get_text
#endif

#ifdef yyget_lineno
#define S1_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno S1_get_lineno
#endif

#ifdef yyset_lineno
#define S1_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno S1_set_lineno
#endif

#ifdef yywrap
#define S1_wrap_ALREADY_DEFINED
#else
#define yywrap S1_wrap
#endif

#ifdef yyalloc
#define S1_alloc_ALREADY_DEFINED
#else
#define yyalloc S1_alloc
#endif

#ifdef yyrealloc
#define S1_realloc_ALREADY_DEFINED
#else
#define yyrealloc S1_realloc
#endif

#ifdef yyfree
#define S1_free_ALREADY_DEFINED
#else
#define yyfree S1_free
#endif

#ifdef yytext
#define S1_text_ALREADY_DEFINED
#else
#define yytext S1_text
#endif

#ifdef yyleng
#define S1_leng_ALREADY_DEFINED
#else
#define yyleng S1_leng
#endif

#ifdef yyin
#define S1_in_ALREADY_DEFINED
#else
#define yyin S1_in
#endif

#ifdef yyout
#define S1_out_ALREADY_DEFINED
#else
#define yyout S1_out
#endif

#ifdef yyflexdebug
#define S1_flexdebug_ALREADY_DEFINED
#else
#define yyflexdebug S1_flexdebug
#endif

#ifdef yylineno
#define S1_lineno_ALREADY_DEFINED
#else
#define yylineno S1_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */

# if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#  define YYFLEX_USE_STDINT
# endif
# if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#  define YYFLEX_USE_STDINT
# else
#  if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#   define YYFLEX_USE_STDINT
#  endif
# endif
# ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
# else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#  ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#   ifdef __cplusplus
#include <climits>
#   else
#include <limits.h>
#   endif
#   if UINT_MAX >= 4294967295
#    define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#   endif
#  else
typedef char flex_int8_t;
#  endif
#  ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#  endif
# endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define yybegin(s) (yy_start) = 1 + 2 * (s)
/* Legacy interface */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define yystart() (((yy_start) - 1) / 2)
/* Legacy interfaces */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* The state buf must be large enough to hold one state per character in the main buffer,
 * plus the start state, plus the two end-of-buffer byte states.
 */
#define YY_STATE_BUF_EXTRA_SPACE 3
#define YY_STATE_BUF_SIZE   (YY_BUF_SIZE + YY_STATE_BUF_EXTRA_SPACE)

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *yybuffer;
/* Legacy interface */
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define yyunput(c) yyunput_r( c, (yytext_ptr)  )
/* Legacy interface */
#define unput(c) yyunput_r( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyatbol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static yybuffer * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_current_buffer() ( (yy_buffer_stack)			\
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Legacy interface */
#define YY_CURRENT_BUFFER yy_current_buffer()
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( yybuffer new_buffer  );
yybuffer yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( yybuffer b  );
void yy_flush_buffer ( yybuffer b  );
void yypush_buffer_state ( yybuffer new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( yybuffer b, FILE *file  );
#define yy_flush_current_buffer() yy_flush_buffer( yy_current_buffer() )
#define YY_FLUSH_BUFFER yy_flush_current_buffer()

yybuffer yy_scan_buffer ( char *base, yy_size_t size  );
yybuffer yy_scan_string ( const char *yy_str  );
yybuffer yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) { \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
			yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}
#define yysetbol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}
#define yyatbol() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
/* Legacy interface */
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
#define yy_set_bol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}

/* Begin user sect3 */

#define S1_wrap() (/*CONSTCOND*/1)

#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef const struct yy_trans_info *yy_state_type;

extern int yylineno;
int yylineno = 1;

/* Watch out: yytext_ptr is a variable when yytext is an array,
 * but it's a macro when yytext is a pointer.
 */

extern char *yytext;

#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */
/* START of m4 controls */
/* M4_MODE_NO_NULTRANS */
/* M4_MODE_NO_NULTRANS_FULLTBL */
/* M4_MODE_NULTRANS_FULLSPD */
/* END of m4 controls */

/* START of Flex-generated definitions */
#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
#define YY_JAMBASE 0
#define YY_JAMSTATE 0
#define YY_NUL_EC 128
#define YY_OFFSET_TYPE flex_int32_t
/* END of Flex-generated definitions */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yypanic ( const char* msg  );

struct yy_trans_info
	{
	/* We require that yy_verify and yy_nxt must be of the same size int. */

	YY_OFFSET_TYPE yy_verify;

	/* In cases where its sister yy_verify *is* a "yes, there is
	 * a transition", yy_nxt is the offset (in records) to the
	 * next state.  In most cases where there is no transition,
	 * the value of yy_nxt is irrelevant.  If yy_nxt is the -1th
	 * record of a state, though, then yy_nxt is the action number
	 * for that state.
	 */
	 YY_OFFSET_TYPE yy_nxt;

	};

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	 \
	yyleng = (int) (yy_cp - yy_bp); \
	 \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
 \
	(yy_c_buf_p) = yy_cp;

extern int yyflexdebug;
int yyflexdebug = 0;
/* Legacy interface */
#ifndef yy_flex_debug
#define yy_flex_debug yyflexdebug
#endif

/* %% [2.0] data tables for the DFA are inserted here */

/* footprint: 21960 bytes */

/* m4 controls begin */
/* M4_MODE_HAS_BACKING_UP */
/* M4_MODE_NEED_YY_CP */
/* M4_MODE_NULTRANS_WRAP */
/* m4 controls end */

/* The transition table */
static const struct yy_trans_info yy_transition[2740] = {
{   0,   0},
{   0,2612},
{   0,   0},
{   0,2610},
{   1, 520},

{   2, 520},
{   3, 520},
{   4, 520},
{   5, 520},
{   6, 520},

{   7, 520},
{   8, 520},
{   9, 522},
{  10, 527},
{  11, 551},

{  12, 551},
{  13, 551},
{  14, 520},
{  15, 520},
{  16, 520},

{  17, 520},
{  18, 520},
{  19, 520},
{  20, 520},
{  21, 520},

{  22, 520},
{  23, 520},
{  24, 520},
{  25, 520},
{  26, 520},

{  27, 520},
{  28, 520},
{  29, 520},
{  30, 520},
{  31, 520},

{  32, 522},
{  33, 520},
{  34, 520},
{  35, 520},
{  36, 529},

{  37, 520},
{  38, 520},
{  39, 520},
{  40, 542},
{  41, 544},

{  42, 546},
{  43, 553},
{  44, 548},
{  45, 553},
{  46, 567},

{  47, 569},
{  48, 572},
{  49, 632},
{  50, 632},
{  51, 632},

{  52, 632},
{  53, 632},
{  54, 632},
{  55, 632},
{  56, 632},

{  57, 632},
{  58, 575},
{  59, 577},
{  60, 587},
{  61, 520},

{  62, 590},
{  63, 520},
{  64, 520},
{  65, 691},
{  66, 691},

{  67, 691},
{  68, 691},
{  69, 691},
{  70, 750},
{  71, 809},

{  72, 809},
{  73, 809},
{  74, 809},
{  75, 809},
{  76, 809},

{  77, 842},
{  78, 809},
{  79, 809},
{  80, 809},
{  81, 809},

{  82, 809},
{  83, 901},
{  84, 955},
{  85, 809},
{  86, 809},

{  87,1008},
{  88, 809},
{  89, 809},
{  90, 809},
{  91, 520},

{  92,1012},
{  93, 599},
{  94, 520},
{  95, 612},
{  96, 520},

{  97,1100},
{  98,1100},
{  99,1100},
{ 100,1100},
{ 101,1100},

{ 102,1100},
{ 103,1130},
{ 104,1130},
{ 105,1130},
{ 106,1130},

{ 107,1130},
{ 108,1130},
{ 109,1130},
{ 110,1130},
{ 111,1130},

{ 112,1130},
{ 113,1130},
{ 114,1130},
{ 115,1130},
{ 116,1130},

{ 117,1130},
{ 118,1130},
{ 119,1130},
{ 120,1130},
{ 121,1130},

{ 122,1130},
{ 123, 520},
{ 124, 658},
{ 125, 660},
{ 126, 520},

{ 127, 520},
{ 128, 520},
{   0,   0},
{   0,2480},
{   1, 390},

{   2, 390},
{   3, 390},
{   4, 390},
{   5, 390},
{   6, 390},

{   7, 390},
{   8, 390},
{   9, 392},
{  10, 397},
{  11, 421},

{  12, 421},
{  13, 421},
{  14, 390},
{  15, 390},
{  16, 390},

{  17, 390},
{  18, 390},
{  19, 390},
{  20, 390},
{  21, 390},

{  22, 390},
{  23, 390},
{  24, 390},
{  25, 390},
{  26, 390},

{  27, 390},
{  28, 390},
{  29, 390},
{  30, 390},
{  31, 390},

{  32, 392},
{  33, 390},
{  34, 390},
{  35, 390},
{  36, 399},

{  37, 390},
{  38, 390},
{  39, 390},
{  40, 412},
{  41, 414},

{  42, 416},
{  43, 423},
{  44, 418},
{  45, 423},
{  46, 437},

{  47, 439},
{  48, 442},
{  49, 502},
{  50, 502},
{  51, 502},

{  52, 502},
{  53, 502},
{  54, 502},
{  55, 502},
{  56, 502},

{  57, 502},
{  58, 445},
{  59, 447},
{  60, 457},
{  61, 390},

{  62, 460},
{  63, 390},
{  64, 390},
{  65, 561},
{  66, 561},

{  67, 561},
{  68, 561},
{  69, 561},
{  70, 620},
{  71, 679},

{  72, 679},
{  73, 679},
{  74, 679},
{  75, 679},
{  76, 679},

{  77, 712},
{  78, 679},
{  79, 679},
{  80, 679},
{  81, 679},

{  82, 679},
{  83, 771},
{  84, 825},
{  85, 679},
{  86, 679},

{  87, 878},
{  88, 679},
{  89, 679},
{  90, 679},
{  91, 390},

{  92, 882},
{  93, 469},
{  94, 390},
{  95, 482},
{  96, 390},

{  97, 970},
{  98, 970},
{  99, 970},
{ 100, 970},
{ 101, 970},

{ 102, 970},
{ 103,1000},
{ 104,1000},
{ 105,1000},
{ 106,1000},

{ 107,1000},
{ 108,1000},
{ 109,1000},
{ 110,1000},
{ 111,1000},

{ 112,1000},
{ 113,1000},
{ 114,1000},
{ 115,1000},
{ 116,1000},

{ 117,1000},
{ 118,1000},
{ 119,1000},
{ 120,1000},
{ 121,1000},

{ 122,1000},
{ 123, 390},
{ 124, 528},
{ 125, 530},
{ 126, 390},

{ 127, 390},
{ 128, 390},
{   0,   0},
{   0,2350},
{   1, 402},

{   2, 402},
{   3, 402},
{   4, 402},
{   5, 402},
{   6, 402},

{   7, 402},
{   8, 402},
{   9, 402},
{  10, 402},
{  11, 402},

{  12, 402},
{  13, 402},
{  14, 402},
{  15, 402},
{  16, 402},

{  17, 402},
{  18, 402},
{  19, 402},
{  20, 402},
{  21, 402},

{  22, 402},
{  23, 402},
{  24, 402},
{  25, 402},
{  26, 402},

{  27, 402},
{  28, 402},
{  29, 402},
{  30, 402},
{  31, 402},

{  32, 402},
{  33, 402},
{  34, 402},
{  35, 402},
{  36, 402},

{  37, 402},
{  38, 402},
{  39, 402},
{  40, 402},
{  41, 402},

{  42, 402},
{  43, 402},
{  44, 402},
{  45, 402},
{  46, 402},

{  47, 402},
{  48, 402},
{  49, 402},
{  50, 402},
{  51, 402},

{  52, 402},
{  53, 402},
{  54, 402},
{  55, 402},
{  56, 402},

{  57, 402},
{  58, 402},
{  59, 402},
{  60, 402},
{  61, 402},

{  62, 402},
{  63, 402},
{  64, 402},
{  65, 402},
{  66, 402},

{  67, 402},
{  68, 402},
{  69, 402},
{  70, 402},
{  71, 402},

{  72, 402},
{  73, 402},
{  74, 402},
{  75, 402},
{  76, 402},

{  77, 402},
{  78, 402},
{  79, 402},
{  80, 402},
{  81, 402},

{  82, 402},
{  83, 402},
{  84, 402},
{  85, 402},
{  86, 402},

{  87, 402},
{  88, 402},
{  89, 402},
{  90, 402},
{  91, 402},

{  92, 402},
{  93, 402},
{  94, 402},
{  95, 402},
{  96, 402},

{  97, 402},
{  98, 402},
{  99, 402},
{ 100, 402},
{ 101, 402},

{ 102, 402},
{ 103, 402},
{ 104, 402},
{ 105, 402},
{ 106, 402},

{ 107, 402},
{ 108, 402},
{ 109, 402},
{ 110, 402},
{ 111, 402},

{ 112, 402},
{ 113, 402},
{ 114, 402},
{ 115, 402},
{ 116, 402},

{ 117, 402},
{ 118, 402},
{ 119, 402},
{ 120, 402},
{ 121, 402},

{ 122, 402},
{ 123, 402},
{ 124, 402},
{ 125, 402},
{ 126, 402},

{ 127, 402},
{ 128, 402},
{   0,   0},
{   0,2220},
{   1, 272},

{   2, 272},
{   3, 272},
{   4, 272},
{   5, 272},
{   6, 272},

{   7, 272},
{   8, 272},
{   9, 272},
{  10, 272},
{  11, 272},

{  12, 272},
{  13, 272},
{  14, 272},
{  15, 272},
{  16, 272},

{  17, 272},
{  18, 272},
{  19, 272},
{  20, 272},
{  21, 272},

{  22, 272},
{  23, 272},
{  24, 272},
{  25, 272},
{  26, 272},

{  27, 272},
{  28, 272},
{  29, 272},
{  30, 272},
{  31, 272},

{  32, 272},
{  33, 272},
{  34, 272},
{  35, 272},
{  36, 272},

{  37, 272},
{  38, 272},
{  39, 272},
{  40, 272},
{  41, 272},

{  42, 272},
{  43, 272},
{  44, 272},
{  45, 272},
{  46, 272},

{  47, 272},
{  48, 272},
{  49, 272},
{  50, 272},
{  51, 272},

{  52, 272},
{  53, 272},
{  54, 272},
{  55, 272},
{  56, 272},

{  57, 272},
{  58, 272},
{  59, 272},
{  60, 272},
{  61, 272},

{  62, 272},
{  63, 272},
{  64, 272},
{  65, 272},
{  66, 272},

{  67, 272},
{  68, 272},
{  69, 272},
{  70, 272},
{  71, 272},

{  72, 272},
{  73, 272},
{  74, 272},
{  75, 272},
{  76, 272},

{  77, 272},
{  78, 272},
{  79, 272},
{  80, 272},
{  81, 272},

{  82, 272},
{  83, 272},
{  84, 272},
{  85, 272},
{  86, 272},

{  87, 272},
{  88, 272},
{  89, 272},
{  90, 272},
{  91, 272},

{  92, 272},
{  93, 272},
{  94, 272},
{  95, 272},
{  96, 272},

{  97, 272},
{  98, 272},
{  99, 272},
{ 100, 272},
{ 101, 272},

{ 102, 272},
{ 103, 272},
{ 104, 272},
{ 105, 272},
{ 106, 272},

{ 107, 272},
{ 108, 272},
{ 109, 272},
{ 110, 272},
{ 111, 272},

{ 112, 272},
{ 113, 272},
{ 114, 272},
{ 115, 272},
{ 116, 272},

{ 117, 272},
{ 118, 272},
{ 119, 272},
{ 120, 272},
{ 121, 272},

{ 122, 272},
{ 123, 272},
{ 124, 272},
{ 125, 272},
{ 126, 272},

{ 127, 272},
{ 128, 272},
{   0,  25},
{   0,2090},
{   0,   5},

{   0,2088},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,  15},

{   0,2083},
{   0,  18},
{   0,2081},
{   0,   0},
{   9, 610},

{  10, 640},
{  11, 640},
{  12, 640},
{  13, 640},
{   9, 635},

{  10, 727},
{  11, 635},
{  12, 635},
{  13, 635},
{   0,  10},

{   0,2068},
{   0,  11},
{   0,2066},
{   0,   8},
{   0,2064},

{   0,  16},
{   0,2062},
{   0,   0},
{   0,  23},
{   0,2059},

{   0,  25},
{   0,2057},
{  32, 610},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  32, 635},
{   9, 611},
{  10, 611},

{  11, 611},
{  12, 611},
{  13, 611},
{  36, 138},
{   0,  19},

{   0,2043},
{   0,  25},
{   0,2041},
{   0,   0},
{   0,   7},

{   0,2038},
{   0,   0},
{   0,   1},
{   0,2035},
{   0,   6},

{   0,2033},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  40, 137},
{  32, 611},
{   0,   0},
{  41, 150},
{   0,  14},

{   0,2023},
{  42, 150},
{   0,  13},
{   0,2020},
{   0,   0},

{  44, 161},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,  22},
{   0,2011},
{   0,   0},
{  48, 703},

{  49, 718},
{  50, 718},
{  51, 718},
{  52, 718},
{  53, 718},

{  54, 718},
{  55, 718},
{  56, 718},
{  57, 718},
{   0,  12},

{   0,1998},
{  46, 170},
{   0,   0},
{  43, 709},
{  47, 227},

{  45, 709},
{   0,   0},
{   0,   0},
{  48, 724},
{  49, 784},

{  50, 784},
{  51, 784},
{  52, 784},
{  53, 784},
{  54, 784},

{  55, 784},
{  56, 784},
{  57, 784},
{   0,   0},
{   0,   7},

{   0,1978},
{  58, 236},
{   0,   0},
{   0,   0},
{  59, 236},

{  65, 807},
{  66, 807},
{  67, 807},
{  68, 807},
{  69, 807},

{  70, 807},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  60, 258},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  62, 281},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   4},
{   0,1952},
{   0,  21},
{   0,1950},
{   0,  26},

{   0,1948},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,  18},

{   0,1943},
{   0,   0},
{  97, 807},
{  98, 807},
{  99, 807},

{ 100, 807},
{ 101, 807},
{ 102, 807},
{  43, 649},
{   0,   0},

{  45, 649},
{   0,  10},
{   0,1931},
{  48, 785},
{  49, 857},

{  50, 857},
{  51, 857},
{  52, 857},
{  53, 857},
{  54, 857},

{  55, 857},
{  56, 857},
{  57, 857},
{   0,   2},
{   0,1919},

{  93, 361},
{   0,  11},
{   0,1916},
{   0,   8},
{   0,1914},

{  65, 747},
{  66, 747},
{  67, 747},
{  68, 747},
{  69, 747},

{  70, 747},
{  36,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  95, 350},
{   0,  16},
{   0,1901},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  40,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  97, 747},
{  98, 747},
{  99, 747},

{ 100, 747},
{ 101, 747},
{ 102, 747},
{  41,   0},
{   0,  19},

{   0,1873},
{  42,   0},
{  48, 688},
{  49, 688},
{  50, 688},

{  51, 688},
{  52, 688},
{  53, 688},
{  54, 688},
{  55, 688},

{  56, 688},
{  57, 688},
{   0,   2},
{   0,1860},
{   0,   0},

{   0,   0},
{  44,   0},
{   0,   0},
{   0,   0},
{  65, 836},

{  66, 836},
{  67, 836},
{  68, 836},
{  69, 836},
{  70, 836},

{  71, 874},
{  72, 874},
{  73, 874},
{  74, 874},
{  75, 874},

{  76, 874},
{  77, 874},
{  78, 874},
{  79, 874},
{  80, 874},

{  81, 874},
{  82, 874},
{  83, 874},
{  84, 874},
{  85, 874},

{  86, 874},
{  87, 874},
{  88, 874},
{  89, 874},
{  90, 874},

{ 124, 335},
{  46,   0},
{   0,   0},
{ 125, 335},
{   0,   0},

{   0,   0},
{  97, 688},
{  98, 688},
{  99, 688},
{ 100, 688},

{ 101, 688},
{ 102, 688},
{   0,   0},
{   0,   0},
{   0,1814},

{   0,   0},
{  48, 629},
{  49, 629},
{  50, 629},
{  51, 629},

{  52, 629},
{  53, 629},
{  54, 629},
{  55, 629},
{  56, 629},

{  57, 629},
{   0,   2},
{   0,1801},
{   0,   1},
{   0,1799},

{   0,   6},
{   0,1797},
{   0,   0},
{  65, 777},
{  66, 777},

{  67, 777},
{  68, 777},
{  69, 777},
{  70, 777},
{  71, 815},

{  72, 815},
{  73, 815},
{  74, 815},
{  75, 815},
{  76, 815},

{  77, 815},
{  78, 815},
{  79, 815},
{  80, 815},
{  81, 815},

{  82, 815},
{  83, 815},
{  84, 815},
{  85, 815},
{  86, 815},

{  87, 815},
{  88, 815},
{  89, 815},
{  90, 815},
{   0,   2},

{   0,1768},
{  47,1044},
{   0,  14},
{   0,1765},
{   0,   0},

{  97, 629},
{  98, 629},
{  99, 629},
{ 100, 629},
{ 101, 629},

{ 102, 629},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{ 114, 154},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  58,   0},
{   0,  13},
{   0,1739},

{  59,   0},
{   0,   0},
{  65, 756},
{  66, 756},
{  67, 756},

{  68, 756},
{  69, 756},
{  70, 756},
{  71, 756},
{  72, 756},

{  73, 756},
{  74, 756},
{  75, 756},
{  76, 756},
{  77, 756},

{  78, 756},
{  79, 756},
{  80, 756},
{  81, 756},
{  82, 756},

{  83, 756},
{  84, 756},
{  85, 756},
{  86, 756},
{  87, 756},

{  88, 756},
{  89, 756},
{  90, 756},
{   0,   2},
{   0,1709},

{   0,   0},
{   0,   0},
{   0,1706},
{  60,   0},
{   0,   0},

{  65, 723},
{  66, 723},
{  67, 723},
{  68, 723},
{  69, 723},

{  70, 723},
{  71, 723},
{  72, 723},
{  73, 723},
{  74, 723},

{  75, 723},
{  76, 723},
{  77, 723},
{  78, 723},
{  79, 723},

{  80, 723},
{  81, 723},
{  82, 723},
{  83, 723},
{  84, 723},

{  85, 723},
{  86, 723},
{  87, 723},
{  88, 723},
{  89, 723},

{  90, 723},
{  62,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,1673},
{   0,   0},
{   0,1671},
{   0,   0},
{   0,   0},

{   0,1668},
{   0,   0},
{   0,1666},
{   0,   0},
{   0,   0},

{   0,1663},
{   0,   0},
{   0,1661},
{   0,   0},
{   0,   0},

{   0,   0},
{ 111,  95},
{   0,   2},
{   0,1655},
{   0,   0},

{   0,  20},
{   0,1652},
{   0,  22},
{   0,1650},
{   0,  12},

{   0,1648},
{   0,   0},
{   0,   0},
{   0,   0},
{  65, 664},

{  66, 664},
{  67, 664},
{  68, 664},
{  69, 664},
{  70, 664},

{  71, 664},
{  72, 664},
{  73, 664},
{  74, 664},
{  75, 664},

{  76, 664},
{  77, 664},
{  78, 664},
{  79, 664},
{  80, 664},

{  81, 664},
{  82, 664},
{  83, 664},
{  84, 664},
{  85, 664},

{  86, 664},
{  87, 664},
{  88, 664},
{  89, 664},
{  90, 664},

{   0,   4},
{   0,1617},
{   0,  21},
{   0,1615},
{   0,   0},

{   0,1613},
{  97,  38},
{   0,   0},
{   0,   0},
{   0,1609},

{   0,   0},
{   0,   0},
{   0,1606},
{   0,   0},
{   0,   0},

{   0,   2},
{   0,1602},
{ 105,1066},
{   0,   0},
{   0,  25},

{   0,1598},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{ 117,  41},
{   0,   0},
{  65, 610},
{  66, 610},

{  67, 610},
{  68, 610},
{  69, 610},
{  70, 610},
{  71, 610},

{  72, 610},
{  73, 610},
{  74, 610},
{  75, 610},
{  76, 610},

{  77, 610},
{  78, 610},
{  79, 610},
{  80, 610},
{  81, 610},

{  82, 610},
{  83, 610},
{  84, 610},
{  85, 610},
{  86, 610},

{  87, 610},
{  88, 610},
{  89, 610},
{  90, 610},
{  34, -54},

{ 110,1033},
{ 101,1023},
{ 100,1021},
{  92,1014},
{  39, -54},

{ 110,1028},
{  93,   0},
{   0,   0},
{ 116,1031},
{   0,   0},

{  95,   0},
{   0,   0},
{ 104, -11},
{   0,   0},
{ 117,1026},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{ 117,  -8},
{  65, 557},
{  66, 557},
{  67, 557},
{  68, 557},

{  69, 557},
{  70, 557},
{  71, 557},
{  72, 557},
{  73, 557},

{  74, 557},
{  75, 557},
{  76, 557},
{  77, 557},
{  78, 557},

{  79, 557},
{  80, 557},
{  81, 557},
{  82, 557},
{  83, 557},

{  84, 557},
{  85, 557},
{  86, 557},
{  87, 557},
{  88, 557},

{  89, 557},
{  90, 557},
{   0,   3},
{   0,1510},
{  97, -65},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{ 101, -59},
{  98, -54},
{ 114, -93},

{ 111, -64},
{   0,   0},
{ 102, -54},
{   0,   0},
{   0,   0},

{ 124,   0},
{   0,   0},
{   0,   0},
{ 125,   0},
{ 117, -62},

{ 110, -54},
{   0,   0},
{   0,   0},
{   0,   0},
{ 114, -54},

{   0,   0},
{ 116, -54},
{   0,   3},
{   0,1480},
{   0,   5},

{   0,1478},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   9,   0},

{  10,  30},
{  11,  30},
{  12,  30},
{  13,  30},
{   0,   0},

{   0,   0},
{  48, 279},
{  49, 279},
{  50, 279},
{  51, 279},

{  52, 279},
{  53, 279},
{  54, 279},
{  55, 279},
{  56, 279},

{  57, 279},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,  23},

{   0,1448},
{   0,   0},
{  32,   0},
{  65, 279},
{  66, 279},

{  67, 279},
{  68, 279},
{  69, 279},
{  70, 279},
{   9,   0},

{  10,   0},
{  11,   0},
{  12,   0},
{  13,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,1430},
{   0,   0},

{   0,1428},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  32,   0},
{   0,   0},
{   0,   0},

{  97, 519},
{  98, 519},
{  99, 519},
{ 100, 519},
{ 101, 519},

{ 102, 519},
{ 103, 557},
{ 104, 557},
{ 105, 557},
{ 106, 557},

{ 107, 557},
{ 108, 557},
{ 109, 557},
{ 110, 557},
{ 111, 557},

{ 112, 557},
{ 113, 557},
{ 114, 557},
{ 115, 557},
{ 116, 557},

{ 117, 557},
{ 118, 557},
{ 119, 557},
{ 120, 557},
{ 121, 557},

{ 122, 557},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  97, 527},
{  98, 527},
{  99, 527},
{ 100, 527},
{ 101, 527},

{ 102, 527},
{ 103, 527},
{ 104, 527},
{ 105, 527},
{ 106, 527},

{ 107, 527},
{ 108, 527},
{ 109, 527},
{ 110, 527},
{ 111, 527},

{ 112, 527},
{ 113, 527},
{ 114, 527},
{ 115, 527},
{ 116, 527},

{ 117, 527},
{ 118, 527},
{ 119, 527},
{ 120, 527},
{ 121, 527},

{ 122, 527},
{   0,  15},
{   0,1356},
{   0,   7},
{   0,1354},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   9, -92},
{  10,   0},
{  11, -92},
{  12, -92},

{  13, -92},
{   0,   0},
{   0,   0},
{   0,   7},
{   0,1339},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,1329},

{   0,   0},
{ 101,-233},
{ 104,-236},
{   0,   0},
{  32, -92},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   7},
{   0,1314},

{ 117,-233},
{   0,   0},
{  43,  25},
{   0,   0},
{  45,  25},

{   0,   0},
{   0,   0},
{  48,   0},
{  49,  15},
{  50,  15},

{  51,  15},
{  52,  15},
{  53,  15},
{  54,  15},
{  55,  15},

{  56,  15},
{  57,  15},
{  43,  10},
{   0,   0},
{  45,  10},

{   0,   0},
{   0,   0},
{  48, 472},
{  49, 510},
{  50, 510},

{  51, 510},
{  52, 510},
{  53, 510},
{  54, 510},
{  55, 510},

{  56, 510},
{  57, 510},
{  48, -25},
{  49, -10},
{  50, -10},

{  51, -10},
{  52, -10},
{  53, -10},
{  54, -10},
{  55, -10},

{  56, -10},
{  57, -10},
{  43, -15},
{   0,   0},
{  45, -15},

{   0,   0},
{   0,   0},
{  48,   0},
{  49,  60},
{  50,  60},

{  51,  60},
{  52,  60},
{  53,  60},
{  54,  60},
{  55,  60},

{  56,  60},
{  57,  60},
{   0,   0},
{   0,   7},
{   0,1254},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  65,  83},

{  66,  83},
{  67,  83},
{  68,  83},
{  69,  83},
{  70,  83},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,  24},
{   0,1231},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  97,  83},
{  98,  83},
{  99,  83},
{ 100,  83},

{ 101,  83},
{ 102,  83},
{  43, -75},
{   0,   0},
{  45, -75},

{   0,   0},
{   0,   0},
{  48,  61},
{  49, 133},
{  50, 133},

{  51, 133},
{  52, 133},
{  53, 133},
{  54, 133},
{  55, 133},

{  56, 133},
{  57, 133},
{   0,   0},
{   0,   0},
{   0,   7},

{   0,1193},
{   0,   0},
{   0,   0},
{   0,   0},
{  65,  23},

{  66,  23},
{  67,  23},
{  68,  23},
{  69,  23},
{  70,  23},

{  48,   0},
{  49,   0},
{  50,   0},
{  51,   0},
{  52,   0},

{  53,   0},
{  54,   0},
{  55,   0},
{  56,   0},
{  57,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  65,   0},
{  66,   0},
{  67,   0},

{  68,   0},
{  69,   0},
{  70,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  97,  23},
{  98,  23},
{  99,  23},
{ 100,  23},

{ 101,  23},
{ 102,  23},
{   0,   0},
{  43,-136},
{   0,   0},

{  45,-136},
{   0,   0},
{   0,   0},
{  48,   0},
{  49,  72},

{  50,  72},
{  51,  72},
{  52,  72},
{  53,  72},
{  54,  72},

{  55,  72},
{  56,  72},
{  57,  72},
{   0,   0},
{  97,   0},

{  98,   0},
{  99,   0},
{ 100,   0},
{ 101,   0},
{ 102,   0},

{  65, -38},
{  66, -38},
{  67, -38},
{  68, -38},
{  69, -38},

{  70, -38},
{   0,   7},
{   0,1121},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  97, -38},
{  98, -38},
{  99, -38},

{ 100, -38},
{ 101, -38},
{ 102, -38},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   2},

{   0,1083},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  43,-208},
{   0,   0},
{  45,-208},
{   0,   0},
{   0,   0},

{  48, -72},
{  49,   0},
{  50,   0},
{  51,   0},
{  52,   0},

{  53,   0},
{  54,   0},
{  55,   0},
{  56,   0},
{  57,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  65,-110},
{  66,-110},
{  67,-110},

{  68,-110},
{  69,-110},
{  70,-110},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   2},
{   0,1045},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  48,-148},
{  49,-148},

{  50,-148},
{  51,-148},
{  52,-148},
{  53,-148},
{  54,-148},

{  55,-148},
{  56,-148},
{  57,-148},
{   0,   0},
{  97,-110},

{  98,-110},
{  99,-110},
{ 100,-110},
{ 101,-110},
{ 102,-110},

{  65,   0},
{  66,   0},
{  67,   0},
{  68,   0},
{  69,   0},

{  70,   0},
{  71,  38},
{  72,  38},
{  73,  38},
{  74,  38},

{  75,  38},
{  76,  38},
{  77,  38},
{  78,  38},
{  79,  38},

{  80,  38},
{  81,  38},
{  82,  38},
{  83,  38},
{  84,  38},

{  85,  38},
{  86,  38},
{  87,  38},
{  88,  38},
{  89,  38},

{  90,  38},
{   0,   3},
{   0, 991},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  97,-148},
{  98,-148},
{  99,-148},

{ 100,-148},
{ 101,-148},
{ 102,-148},
{  65,   0},
{  66,   0},

{  67,   0},
{  68,   0},
{  69,   0},
{  70,   0},
{  71,   0},

{  72,   0},
{  73,   0},
{  74,   0},
{  75,   0},
{  76,   0},

{  77,   0},
{  78,   0},
{  79,   0},
{  80,   0},
{  81,   0},

{  82,   0},
{  83,   0},
{  84,   0},
{  85,   0},
{  86,   0},

{  87,   0},
{  88,   0},
{  89,   0},
{  90,   0},
{   0,   3},

{   0, 953},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  48,-240},
{  49,-240},
{  50,-240},
{  51,-240},
{  52,-240},

{  53,-240},
{  54,-240},
{  55,-240},
{  56,-240},
{  57,-240},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  65,-240},
{  66,-240},
{  67,-240},

{  68,-240},
{  69,-240},
{  70,-240},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  97,   0},

{  98,   0},
{  99,   0},
{ 100,   0},
{ 101,   0},
{ 102,   0},

{ 103,  38},
{ 104,  38},
{ 105,  38},
{ 106,  38},
{ 107,  38},

{ 108,  38},
{ 109,  38},
{ 110,  38},
{ 111,  38},
{ 112,  38},

{ 113,  38},
{ 114,  38},
{ 115,  38},
{ 116,  38},
{ 117,  38},

{ 118,  38},
{ 119,  38},
{ 120,  38},
{ 121,  38},
{ 122,  38},

{   0,   7},
{   0, 867},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  97,   0},
{  98,   0},
{  99,   0},

{ 100,   0},
{ 101,   0},
{ 102,   0},
{ 103,   0},
{ 104,   0},

{ 105,   0},
{ 106,   0},
{ 107,   0},
{ 108,   0},
{ 109,   0},

{ 110,   0},
{ 111,   0},
{ 112,   0},
{ 113,   0},
{ 114,   0},

{ 115,   0},
{ 116,   0},
{ 117,   0},
{ 118,   0},
{ 119,   0},

{ 120,   0},
{ 121,   0},
{ 122,   0},
{   0,   7},
{   0, 829},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  43,-462},

{   0,   0},
{  45,-462},
{   0,   0},
{   0,   0},
{  48,   0},

{  49,  38},
{  50,  38},
{  51,  38},
{  52,  38},
{  53,  38},

{  54,  38},
{  55,  38},
{  56,  38},
{  57,  38},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{  43,-500},
{   0,   0},
{  45,-500},

{   0,   0},
{   0,   0},
{  48, -38},
{  49,   0},
{  50,   0},

{  51,   0},
{  52,   0},
{  53,   0},
{  54,   0},
{  55,   0},

{  56,   0},
{  57,   0},
{   0,   9},
{   0, 770},
{   1, 250},

{   2, 250},
{   3, 250},
{   4, 250},
{   5, 250},
{   6, 250},

{   7, 250},
{   8, 250},
{   9, 250},
{   0,   0},
{  11, 250},

{  12, 250},
{  13, 250},
{  14, 250},
{  15, 250},
{  16, 250},

{  17, 250},
{  18, 250},
{  19, 250},
{  20, 250},
{  21, 250},

{  22, 250},
{  23, 250},
{  24, 250},
{  25, 250},
{  26, 250},

{  27, 250},
{  28, 250},
{  29, 250},
{  30, 250},
{  31, 250},

{  32, 250},
{  33, 250},
{  34, 250},
{  35, 250},
{  36, 250},

{  37, 250},
{  38, 250},
{  39, 250},
{  40, 250},
{  41, 250},

{  42, 250},
{  43, 250},
{  44, 250},
{  45, 250},
{  46, 250},

{  47, 380},
{  48, 250},
{  49, 250},
{  50, 250},
{  51, 250},

{  52, 250},
{  53, 250},
{  54, 250},
{  55, 250},
{  56, 250},

{  57, 250},
{  58, 250},
{  59, 250},
{  60, 250},
{  61, 250},

{  62, 250},
{  63, 250},
{  64, 250},
{  65, 250},
{  66, 250},

{  67, 250},
{  68, 250},
{  69, 250},
{  70, 250},
{  71, 250},

{  72, 250},
{  73, 250},
{  74, 250},
{  75, 250},
{  76, 250},

{  77, 250},
{  78, 250},
{  79, 250},
{  80, 250},
{  81, 250},

{  82, 250},
{  83, 250},
{  84, 250},
{  85, 250},
{  86, 250},

{  87, 250},
{  88, 250},
{  89, 250},
{  90, 250},
{  91, 250},

{  92, 250},
{  93, 250},
{  94, 250},
{  95, 250},
{  96, 250},

{  97, 250},
{  98, 250},
{  99, 250},
{ 100, 250},
{ 101, 250},

{ 102, 250},
{ 103, 250},
{ 104, 250},
{ 105, 250},
{ 106, 250},

{ 107, 250},
{ 108, 250},
{ 109, 250},
{ 110, 250},
{ 111, 250},

{ 112, 250},
{ 113, 250},
{ 114, 250},
{ 115, 250},
{ 116, 250},

{ 117, 250},
{ 118, 250},
{ 119, 250},
{ 120, 250},
{ 121, 250},

{ 122, 250},
{ 123, 250},
{ 124, 250},
{ 125, 250},
{ 126, 250},

{ 127, 250},
{ 128, 250},
{   0,  17},
{   0, 640},
{   0,   0},

{   0, 638},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  34,-1014},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{  39,-1014},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  70,-973},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{  77,-969},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{  83,-966},
{  84,-790},
{   0,   0},
{   0,   0},

{  87,-788},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{  98,-1014},
{   0,   0},

{   0,   0},
{   0,   0},
{ 102,-1014},
{   0,   0},
{   0,   0},

{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},
{   0,   0},

{ 110,-1014},
{   0,   0},
{   0,   0},
{   0,   0},
{ 114,-1014},

{   0,   0},
{ 116,-1014},
{   0,   9},
{   0, 520},
{   1,   0},

{   2,   0},
{   3,   0},
{   4,   0},
{   5,   0},
{   6,   0},

{   7,   0},
{   8,   0},
{   9,   0},
{   0,   0},
{  11,   0},

{  12,   0},
{  13,   0},
{  14,   0},
{  15,   0},
{  16,   0},

{  17,   0},
{  18,   0},
{  19,   0},
{  20,   0},
{  21,   0},

{  22,   0},
{  23,   0},
{  24,   0},
{  25,   0},
{  26,   0},

{  27,   0},
{  28,   0},
{  29,   0},
{  30,   0},
{  31,   0},

{  32,   0},
{  33,   0},
{  34,   0},
{  35,   0},
{  36,   0},

{  37,   0},
{  38,   0},
{  39,   0},
{  40,   0},
{  41,   0},

{  42,   0},
{  43,   0},
{  44,   0},
{  45,   0},
{  46,   0},

{  47, 130},
{  48,   0},
{  49,   0},
{  50,   0},
{  51,   0},

{  52,   0},
{  53,   0},
{  54,   0},
{  55,   0},
{  56,   0},

{  57,   0},
{  58,   0},
{  59,   0},
{  60,   0},
{  61,   0},

{  62,   0},
{  63,   0},
{  64,   0},
{  65,   0},
{  66,   0},

{  67,   0},
{  68,   0},
{  69,   0},
{  70,   0},
{  71,   0},

{  72,   0},
{  73,   0},
{  74,   0},
{  75,   0},
{  76,   0},

{  77,   0},
{  78,   0},
{  79,   0},
{  80,   0},
{  81,   0},

{  82,   0},
{  83,   0},
{  84,   0},
{  85,   0},
{  86,   0},

{  87,   0},
{  88,   0},
{  89,   0},
{  90,   0},
{  91,   0},

{  92,   0},
{  93,   0},
{  94,   0},
{  95,   0},
{  96,   0},

{  97,   0},
{  98,   0},
{  99,   0},
{ 100,   0},
{ 101,   0},

{ 102,   0},
{ 103,   0},
{ 104,   0},
{ 105,   0},
{ 106,   0},

{ 107,   0},
{ 108,   0},
{ 109,   0},
{ 110,   0},
{ 111,   0},

{ 112,   0},
{ 113,   0},
{ 114,   0},
{ 115,   0},
{ 116,   0},

{ 117,   0},
{ 118,   0},
{ 119,   0},
{ 120,   0},
{ 121,   0},

{ 122,   0},
{ 123,   0},
{ 124,   0},
{ 125,   0},
{ 126,   0},

{ 127,   0},
{ 128,   0},
{   0,   9},
{   0, 390},
{   1,-130},

{   2,-130},
{   3,-130},
{   4,-130},
{   5,-130},
{   6,-130},

{   7,-130},
{   8,-130},
{   9,-130},
{   0,   0},
{  11,-130},

{  12,-130},
{  13,-130},
{  14,-130},
{  15,-130},
{  16,-130},

{  17,-130},
{  18,-130},
{  19,-130},
{  20,-130},
{  21,-130},

{  22,-130},
{  23,-130},
{  24,-130},
{  25,-130},
{  26,-130},

{  27,-130},
{  28,-130},
{  29,-130},
{  30,-130},
{  31,-130},

{  32,-130},
{  33,-130},
{  34,-130},
{  35,-130},
{  36,-130},

{  37,-130},
{  38,-130},
{  39,-130},
{  40,-130},
{  41,-130},

{  42,-130},
{  43,-130},
{  44,-130},
{  45,-130},
{  46,-130},

{  47, 130},
{  48,-130},
{  49,-130},
{  50,-130},
{  51,-130},

{  52,-130},
{  53,-130},
{  54,-130},
{  55,-130},
{  56,-130},

{  57,-130},
{  58,-130},
{  59,-130},
{  60,-130},
{  61,-130},

{  62,-130},
{  63,-130},
{  64,-130},
{  65,-130},
{  66,-130},

{  67,-130},
{  68,-130},
{  69,-130},
{  70,-130},
{  71,-130},

{  72,-130},
{  73,-130},
{  74,-130},
{  75,-130},
{  76,-130},

{  77,-130},
{  78,-130},
{  79,-130},
{  80,-130},
{  81,-130},

{  82,-130},
{  83,-130},
{  84,-130},
{  85,-130},
{  86,-130},

{  87,-130},
{  88,-130},
{  89,-130},
{  90,-130},
{  91,-130},

{  92,-130},
{  93,-130},
{  94,-130},
{  95,-130},
{  96,-130},

{  97,-130},
{  98,-130},
{  99,-130},
{ 100,-130},
{ 101,-130},

{ 102,-130},
{ 103,-130},
{ 104,-130},
{ 105,-130},
{ 106,-130},

{ 107,-130},
{ 108,-130},
{ 109,-130},
{ 110,-130},
{ 111,-130},

{ 112,-130},
{ 113,-130},
{ 114,-130},
{ 115,-130},
{ 116,-130},

{ 117,-130},
{ 118,-130},
{ 119,-130},
{ 120,-130},
{ 121,-130},

{ 122,-130},
{ 123,-130},
{ 124,-130},
{ 125,-130},
{ 126,-130},

{ 127,-130},
{ 128,-130},
{   0,   9},
{   0, 260},
{   1,-260},

{   2,-260},
{   3,-260},
{   4,-260},
{   5,-260},
{   6,-260},

{   7,-260},
{   8,-260},
{   9,-260},
{   0,   0},
{  11,-260},

{  12,-260},
{  13,-260},
{  14,-260},
{  15,-260},
{  16,-260},

{  17,-260},
{  18,-260},
{  19,-260},
{  20,-260},
{  21,-260},

{  22,-260},
{  23,-260},
{  24,-260},
{  25,-260},
{  26,-260},

{  27,-260},
{  28,-260},
{  29,-260},
{  30,-260},
{  31,-260},

{  32,-260},
{  33,-260},
{  34,-260},
{  35,-260},
{  36,-260},

{  37,-260},
{  38,-260},
{  39,-260},
{  40,-260},
{  41,-260},

{  42,-260},
{  43,-260},
{  44,-260},
{  45,-260},
{  46,-260},

{  47, 130},
{  48,-260},
{  49,-260},
{  50,-260},
{  51,-260},

{  52,-260},
{  53,-260},
{  54,-260},
{  55,-260},
{  56,-260},

{  57,-260},
{  58,-260},
{  59,-260},
{  60,-260},
{  61,-260},

{  62,-260},
{  63,-260},
{  64,-260},
{  65,-260},
{  66,-260},

{  67,-260},
{  68,-260},
{  69,-260},
{  70,-260},
{  71,-260},

{  72,-260},
{  73,-260},
{  74,-260},
{  75,-260},
{  76,-260},

{  77,-260},
{  78,-260},
{  79,-260},
{  80,-260},
{  81,-260},

{  82,-260},
{  83,-260},
{  84,-260},
{  85,-260},
{  86,-260},

{  87,-260},
{  88,-260},
{  89,-260},
{  90,-260},
{  91,-260},

{  92,-260},
{  93,-260},
{  94,-260},
{  95,-260},
{  96,-260},

{  97,-260},
{  98,-260},
{  99,-260},
{ 100,-260},
{ 101,-260},

{ 102,-260},
{ 103,-260},
{ 104,-260},
{ 105,-260},
{ 106,-260},

{ 107,-260},
{ 108,-260},
{ 109,-260},
{ 110,-260},
{ 111,-260},

{ 112,-260},
{ 113,-260},
{ 114,-260},
{ 115,-260},
{ 116,-260},

{ 117,-260},
{ 118,-260},
{ 119,-260},
{ 120,-260},
{ 121,-260},

{ 122,-260},
{ 123,-260},
{ 124,-260},
{ 125,-260},
{ 126,-260},

{ 127,-260},
{ 128,-260},
{   0,   9},
{   0, 130},
{   1,-390},

{   2,-390},
{   3,-390},
{   4,-390},
{   5,-390},
{   6,-390},

{   7,-390},
{   8,-390},
{   9,-390},
{   0,   0},
{  11,-390},

{  12,-390},
{  13,-390},
{  14,-390},
{  15,-390},
{  16,-390},

{  17,-390},
{  18,-390},
{  19,-390},
{  20,-390},
{  21,-390},

{  22,-390},
{  23,-390},
{  24,-390},
{  25,-390},
{  26,-390},

{  27,-390},
{  28,-390},
{  29,-390},
{  30,-390},
{  31,-390},

{  32,-390},
{  33,-390},
{  34,-390},
{  35,-390},
{  36,-390},

{  37,-390},
{  38,-390},
{  39,-390},
{  40,-390},
{  41,-390},

{  42,-390},
{  43,-390},
{  44,-390},
{  45,-390},
{  46,-390},

{  47,   0},
{  48,-390},
{  49,-390},
{  50,-390},
{  51,-390},

{  52,-390},
{  53,-390},
{  54,-390},
{  55,-390},
{  56,-390},

{  57,-390},
{  58,-390},
{  59,-390},
{  60,-390},
{  61,-390},

{  62,-390},
{  63,-390},
{  64,-390},
{  65,-390},
{  66,-390},

{  67,-390},
{  68,-390},
{  69,-390},
{  70,-390},
{  71,-390},

{  72,-390},
{  73,-390},
{  74,-390},
{  75,-390},
{  76,-390},

{  77,-390},
{  78,-390},
{  79,-390},
{  80,-390},
{  81,-390},

{  82,-390},
{  83,-390},
{  84,-390},
{  85,-390},
{  86,-390},

{  87,-390},
{  88,-390},
{  89,-390},
{  90,-390},
{  91,-390},

{  92,-390},
{  93,-390},
{  94,-390},
{  95,-390},
{  96,-390},

{  97,-390},
{  98,-390},
{  99,-390},
{ 100,-390},
{ 101,-390},

{ 102,-390},
{ 103,-390},
{ 104,-390},
{ 105,-390},
{ 106,-390},

{ 107,-390},
{ 108,-390},
{ 109,-390},
{ 110,-390},
{ 111,-390},

{ 112,-390},
{ 113,-390},
{ 114,-390},
{ 115,-390},
{ 116,-390},

{ 117,-390},
{ 118,-390},
{ 119,-390},
{ 120,-390},
{ 121,-390},

{ 122,-390},
{ 123,-390},
{ 124,-390},
{ 125,-390},
{ 126,-390},

{ 127,-390},
{ 128,-390},
{ 129,  27},
{   1,   0},
};

/* Table of pointers to start states. */
static const struct yy_trans_info *yy_start_state_list[5] = {
	&yy_transition[1],
	&yy_transition[3],
	&yy_transition[133],
	&yy_transition[263],
	&yy_transition[393],

};

/* Definitions for backing up.  We don't need them if yyreject()
 * is being used because then we use an alternative backing-up
 * technique instead.
 */
static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of yyreject() which flex missed.
 */
#define yyreject() reject_used_but_not_detected
#define REJECT reject_used_but_not_detected

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

char *yytext;

/* %% [3.0] static declarations conditional on mode switches go here */
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#include "globals.h"
int line_start;
int line_stop;
int debug;
//{LPAREN}    {    }
//{RPAREN}    {    }
//{LBRACE}    {    }
//{RBRACE}    {    }
//{COLON}    {    }
//{LBRACK}    {    }
//{RBRACK}    {    }
//{GT}    {    }
//{LT}    {    }
//{POWER}    {    }
//{PIPE}    {    }
//{SEMICOLON}    {    }
//{ESCAPESEQUENCE}    {    }
//{DOLLAR}    {    }
//{DOT}    {    }
//{COMMA}    {    }
//{DAY}    {    }
//{MONTH}    {    }
//{TIMEZONE}    {    }




#define INITIAL 0
#define line 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_YYUNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#define YY_NO_YYINPUT 1

#ifndef YY_NO_YYINPUT

static int yyinput ( void );
#ifndef __cplusplus
#define input yyinput
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
/*
 * Amount of stuff to slurp up with each read.
 * We assume the stdio library has already
 * chosen a fit size foe whatever platform
 * we're running on.
 */
#define YY_READ_BUF_SIZE BUFSIZ

/* Size of default input buffer. We want to be able to fit two
 * OS-level reads, but efficiency gains as the buffer size
 * increases fall off after that
 */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE	(2 * YY_READ_BUF_SIZE)
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef yyecho

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define yyecho() do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)

#endif
/* Legacy interface */
#define ECHO yyecho()

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yypanic (const char* msg ) {
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Report a fatal error. Legacy interface. */
#ifndef YY_FATAL_ERROR

#define YY_FATAL_ERROR(msg) yypanic( msg )

#endif

/* Legacy interface */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) do {result = yyread(buf, max_size );} while (0)

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */

static int yyread(char *buf, size_t max_size ) {

	int result;
	
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) {
		int c = '*';
		int n;
		for ( n = 0; n < max_size &&
			      (c = getc( yyin )) != EOF && c != '\n'; ++n ) {
			buf[n] = (char) c;
		}
		if ( c == '\n' ) {
			buf[n++] = (char) c;
		}
		if ( c == EOF && ferror( yyin ) ) {
			YY_FATAL_ERROR( "input in flex scanner failed" );
		}
		result = n;
	} else {
		errno=0;
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) {
			if( errno != EINTR) {
				YY_FATAL_ERROR( "input in flex scanner failed" );
				break;
			}
			errno=0;
			clearerr(yyin);
		}
	}

	 return result;
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)

#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#define YY_RULE_SETUP \
		YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) ) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) ) {
			(yy_start) = 1;	/* first start state */
		}
		if ( ! yyin ) {

			yyin = stdin;

		}
		if ( ! yyout ) {

			yyout = stdout;

		}
		if ( yy_current_buffer() == NULL ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
	}

	/* open scope of user declarationns */
	{
/* %% [4.0] user's declarations go here */
#line 74 "scanner.l"




		while ( /*CONSTCOND*/1 ) {		/* loops until end-of-file is reached */

			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	yy_match:
			/* Generate the code to find the next match. */

		{
			const struct yy_trans_info *yy_trans_info;
			YY_CHAR yy_c;

			for ( yy_c = YY_SC_TO_UI(*yy_cp);
			      (yy_trans_info = &yy_current_state[yy_c])->yy_verify == yy_c;
			      yy_c = YY_SC_TO_UI(*++yy_cp) )
			{
				yy_current_state += yy_trans_info->yy_nxt;

		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

			}
		}

	yy_find_action:
			/* code to find the action number goes here */
			yy_act = yy_current_state[-1].yy_nxt;
			
			YY_DO_BEFORE_ACTION;

		do_action:	/* This label is used only to access EOF actions. */

			switch ( yy_act ) { /* beginning of action switch */

			case 0: /* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);

				/* Backing-up info for compressed tables is taken \after/ */
				/* yy_cp has been incremented for the next state. */
				yy_cp = (yy_last_accepting_cpos);
				yy_cp++;
				
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

/* %% [5.0] user actions get inserted here */
	case 1:
YY_RULE_SETUP

#line 76 "scanner.l"
{
	if(yyleng==1){
		printf("{COLON}");
	} else {
		printf("{COLON}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 2:
YY_RULE_SETUP

#line 85 "scanner.l"
{
	if(yyleng==1){
		printf("{UPPER}");
	} else {
		printf("{UPPER}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 3:
YY_RULE_SETUP

#line 93 "scanner.l"
{
	if(yyleng==1){
		printf("{LOWER}");
	} else {
		printf("{LOWER}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 4:
YY_RULE_SETUP

#line 100 "scanner.l"
{
	if(yyleng==1){
		printf("{OR}");
	} else {
		printf("{OR}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 5:
YY_RULE_SETUP

#line 108 "scanner.l"
{
	if(yyleng==1){
		printf("{WS}");
	} else {
		printf("{WS}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 6:
YY_RULE_SETUP

#line 116 "scanner.l"
{
	if(yyleng==1){
		printf("{SEMICOLON}");
	} else {
		printf("{SEMICOLON}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 7:
YY_RULE_SETUP

#line 123 "scanner.l"
{
	if(yyleng==1){
		printf("{INTEGER}");
	} else {
		printf("{INTEGER}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 8:
YY_RULE_SETUP

#line 131 "scanner.l"
{
	if(yyleng==1){
		printf("{STAR}");
	} else {
		printf("{STAR}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 9:
YY_RULE_SETUP

#line 138 "scanner.l"
{
	if(yyleng==1){
		printf("{COMMENT}");
	} else {
		printf("{COMMENT}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 10:
YY_RULE_SETUP

#line 146 "scanner.l"
{
	if(yyleng==1){
		printf("{LPAREN}");
	} else {
		printf("{LPAREN}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 11:
YY_RULE_SETUP

#line 154 "scanner.l"
{
	if(yyleng==1){
		printf("{RPAREN}");
	} else {
		printf("{RPAREN}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 12:
YY_RULE_SETUP

#line 162 "scanner.l"
{
	if(yyleng==1){
		printf("{UNDERSCORE}");
	} else {
		printf("{UNDERSCORE}{%d}",yyleng);
	}
}
	/*LINTED*/break;
	case 13:
YY_RULE_SETUP

#line 170 "scanner.l"
{
	if(yyleng==1){
		printf("{GT}\n");
	} else {
		printf("{GT}{%d}\n",yyleng);
	}
}
	/*LINTED*/break;
	case 14:
YY_RULE_SETUP

#line 177 "scanner.l"
{
	if(yyleng==1){
		printf("{LT}\n");
	} else {
		printf("{LT}{%d}\n",yyleng);
	}
}
	/*LINTED*/break;
	case 15:
/* rule 15 can match eol */
YY_RULE_SETUP

#line 185 "scanner.l"
{
	if(yyleng==1){
		printf("{NL}\n");
	} else {
		printf("{NL}{%d}\n",yyleng);
	}
}
	/*LINTED*/break;
	case 16:
YY_RULE_SETUP

#line 196 "scanner.l"
{
            if(yyleng==1){
                    printf("COMMA\n");
            } else {
                    printf("COMMA{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 17:
YY_RULE_SETUP

#line 205 "scanner.l"
{
            if(yyleng==1){
                    printf("DAY\n");
            } else {
                    printf("DAY{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 18:
YY_RULE_SETUP

#line 213 "scanner.l"
{
            if(yyleng==1){
                    printf("DOLLAR\n");
            } else {
                    printf("DOLLAR{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 19:
YY_RULE_SETUP

#line 221 "scanner.l"
{
            if(yyleng==1){
                    printf("DOT\n");
            } else {
                    printf("DOT{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 20:
YY_RULE_SETUP

#line 229 "scanner.l"
{
            if(yyleng==1){
                    printf("ESCAPESEQUENCE\n");
            } else {
                    printf("ESCAPESEQUENCE{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 21:
YY_RULE_SETUP

#line 242 "scanner.l"
{
            if(yyleng==1){
                    printf("RBRACE\n");
            } else {
                    printf("RBRACE{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 22:
YY_RULE_SETUP

#line 250 "scanner.l"
{
            if(yyleng==1){
                    printf("RBRACK\n");
            } else {
                    printf("RBRACK{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 23:
/* rule 23 can match eol */
YY_RULE_SETUP

#line 258 "scanner.l"
{
            if(yyleng==1){
                    printf("SPACE\n");
            } else {
                    printf("SPACE{%d}\n",yyleng);
            }
    }
	/*LINTED*/break;
	case 24:
YY_RULE_SETUP

#line 270 "scanner.l"
{
            if(yyleng==1){
                    printf("XDIGIT\n");
            } else {
                    printf("XDIGIT{%d}\n",yyleng);
            }
}
	/*LINTED*/break;
	case 25:
YY_RULE_SETUP

#line 278 "scanner.l"
;
	/*LINTED*/break;
	case 26:
YY_RULE_SETUP

#line 279 "scanner.l"
yyecho();
	/*LINTED*/break;


	case YY_STATE_EOF(INITIAL):
		/* FALLTHROUGH */
	case YY_STATE_EOF(line):
		/* FALLTHROUGH */
		yyterminate();

			case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

				if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
					/* We're scanning a new file or input source.  It's
					 * possible that this happened because the user
					 * just pointed yyin at a new source and called
					 * yylex().  If so, then we have to assure
					 * consistency between yy_current_buffer() and our
					 * globals.  Here is the right place to do so, because
					 * this is the first action (other than possibly a
					 * back-up) that will match for the new input source.
					 */
					(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;

					YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;

					YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
				}

				/* Note that here we test for yy_c_buf_p "<=" to the position
				 * of the first EOB in the buffer, since yy_c_buf_p will
				 * already have been incremented past the NUL character
				 * (since all states make transitions on EOB to the
				 * end-of-buffer state).  Contrast this with the test
				 * in input().
				 */
				if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) { /* This was really a NUL. */
					yy_state_type yy_next_state;

					(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

					yy_current_state = yy_get_previous_state(  );

					/* Okay, we're now positioned to make the NUL
					 * transition.  We couldn't have
					 * yy_get_previous_state() go ahead and do it
					 * for us because it doesn't know how to deal
					 * with the possibility of jamming (and we don't
					 * want to build jamming into it because then it
					 * will run more slowly).
					 */

					yy_next_state = yy_try_NUL_trans( yy_current_state );

					yy_bp = (yytext_ptr) + YY_MORE_ADJ;

					if ( yy_next_state ) {
						/* Consume the NUL. */
						yy_cp = ++(yy_c_buf_p);
						yy_current_state = yy_next_state;
						goto yy_match;
					} else {
						yy_cp = (yy_c_buf_p);
						
						goto yy_find_action;
					}
				} else {	/* not a NUL */
					switch ( yy_get_next_buffer(  ) ) {
					case EOB_ACT_END_OF_FILE:
						(yy_did_buffer_switch_on_eof) = 0;

						if ( yywrap(  ) ) {
							/* Note: because we've taken care in
							 * yy_get_next_buffer() to have set up
							 * yytext, we can now set up
							 * yy_c_buf_p so that if some total
							 * hoser (like flex itself) wants to
							 * call the scanner after we return the
							 * YY_NULL, it'll still work - another
							 * YY_NULL will get returned.
							 */
							(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

							yy_act = YY_STATE_EOF(yystart());
							goto do_action;
						} else {
							if ( ! (yy_did_buffer_switch_on_eof) ) {
								YY_NEW_FILE;
							}
						}
						break;
					case EOB_ACT_CONTINUE_SCAN:
						(yy_c_buf_p) =
							(yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_match;

					case EOB_ACT_LAST_MATCH:
						(yy_c_buf_p) =
						&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_find_action;
					} /* end EOB inner switch */
				} /* end if */
				break;
			} /* case YY_END_OF_BUFFER */
			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
			} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer (void)

{
		char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] ) {
		YY_FATAL_ERROR( "fatal flex scanner internal error--end of buffer missed" );
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
		/* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		} else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i ) {
		*(dest++) = *(source++);
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING ) {
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
	} else {
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 ) { /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			yybuffer b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer ) {
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 ) {
					b->yy_buf_size += b->yy_buf_size / 8;
				} else {
					b->yy_buf_size *= 2;
				}
				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
			} else {
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;
			}
			if ( ! b->yy_ch_buf ) {
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );
			}
			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

		}

		if ( num_to_read > YY_READ_BUF_SIZE ) {
			num_to_read = YY_READ_BUF_SIZE;
		}
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 ) {
		if ( number_to_move == YY_MORE_ADJ ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
		} else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	} else {
		ret_val = EOB_ACT_CONTINUE_SCAN;
	}
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		}
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)

{
	yy_state_type yy_current_state;
	char *yy_cp;
	
	/* Generate the code to find the start state. */

yy_current_state = yy_start_state_list[(yy_start)];

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
		/* Generate the code to find the next state. */
		
		yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : YY_NUL_EC)].yy_nxt;
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )

{
	int yy_is_jam;
		/* Generate code for handling NUL's, if needed. */

	/* First, deal with backing up and setting up yy_cp if the scanner
	 * finds that it should JAM on the NUL.
	 *
	 * Only generate a definition for "yy_cp" if we'll generate code
	 * that uses it.  Otherwise lint and the like complain.
	 */
	char *yy_cp = (yy_c_buf_p);

	int yy_c = YY_NUL_EC;

	const struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	/* If we've entered an accepting state, back up; note that
	 * compressed tables have *already* done such backing up, so
	 * we needn't bother with it again.
	 */
	if ( ! yy_is_jam ) {
		
		/* Generate code to keep backing-up information. */

		 if ( yy_current_state[-1].yy_nxt ) {

			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}

	}

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_YYINPUT
int yyinput (void)

{
	int c;
	
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
		} else {
			/* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) ) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart( yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				if ( yywrap(  ) ) {
					return 0;
				}
				if ( ! (yy_did_buffer_switch_on_eof) ) {
					YY_NEW_FILE;
				}
				return yyinput();

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

#endif	/* ifndef YY_NO_YYINPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */

void yyrestart  (FILE * input_file )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	if ( yy_current_buffer() == NULL ) {
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
	        	yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER_LVALUE, input_file );
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */

void yy_switch_to_buffer  (yybuffer  new_buffer )

{
		size_t new_size = 0;
	yy_state_type *new_state_buf = 0;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack ();
	if ( yy_current_buffer() == new_buffer ) {
		return;
	}
	if ( yy_current_buffer() ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)

{
		(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;

	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;

	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */

yybuffer yy_create_buffer  (FILE * file, int  size )

{
	yybuffer b;
	
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if (  b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( b->yy_ch_buf == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */

void yy_delete_buffer (yybuffer  b )

{
	
	if ( b == NULL ) {
		return;
	}
	if ( b == yy_current_buffer() ) {	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (yybuffer) 0;
	}
	if ( b->yy_is_our_buffer ) {
		yyfree( (void *) b->yy_ch_buf  );
	}
	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */

static void yy_init_buffer  (yybuffer  b, FILE * file )

{
	int oerrno = errno;
	
	yy_flush_buffer( b );

	b->yy_input_file = file;

    /* b->yy_input_file should never by NULL but we'll handle it cleanly
	 * on the off chance.
	 */
	if (b->yy_input_file == NULL){
	  b->yy_fill_buffer = 0;
	} else {
	  b->yy_fill_buffer = 1;
	}

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != yy_current_buffer()) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_current_buffer().
 * 
 */

void yy_flush_buffer (yybuffer  b )

{
		if ( b == NULL ) {
		return;
	}
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yyatbol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer() ) {
		yy_load_buffer_state(  );
	}
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */

void yypush_buffer_state (yybuffer new_buffer )

{
		if (new_buffer == NULL) {
		return;
	}
	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( yy_current_buffer() != NULL ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_current_buffer()) {
		(yy_buffer_stack_top)++;
	}
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */

void yypop_buffer_state (void)

{
		if (yy_current_buffer() == NULL) {
		return;
	}
	yy_delete_buffer(yy_current_buffer() );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0) {
		--(yy_buffer_stack_top);
	}
	if (yy_current_buffer() != NULL) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */

static void yyensure_buffer_stack (void)

{
	yy_size_t num_to_alloc;
	
	if ((yy_buffer_stack) == NULL) {
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( (yy_buffer_stack == NULL) ) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {
		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ((yy_buffer_stack) == NULL) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_buffer  (char * base, yy_size_t  size )
{
	yybuffer b;
	
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR ) {
		/* They forgot to leave room for the EOB's. */
		return NULL;
	}
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
	}
	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yyatbol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
yybuffer yy_scan_string (const char * yystr )
{
	
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_bytes  (const char * yybytes, int  _yybytes_len ) {
	yybuffer b;
	char *buf;
	yy_size_t n;
	int i;
	
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( buf == 0 ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
	}
	for ( i = 0; i < _yybytes_len; ++i ) {
		buf[i] = yybytes[i];
	}
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
	}
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

static void yy_push_state (int  _new_state )

{
		if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) ) {
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) ) {
			(yy_start_stack) = (int *) yyalloc( new_size  );

		} else {
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );
		}
		if ( ! (yy_start_stack) ) {
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}
	}
	(yy_start_stack)[(yy_start_stack_ptr)++] = yystart();

	yybegin(_new_state);
}

static void yy_pop_state  (void)

{
		if ( --(yy_start_stack_ptr) < 0 ) {
		YY_FATAL_ERROR( "start-condition stack underflow" );
	}
	yybegin((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do { \
		/* Undo effects of setting up yytext. */ \
		int yyless_macro_arg = (n); \
		YY_LESS_LINENO(yyless_macro_arg);\
			yytext[yyleng] = (yy_hold_char); \
			(yy_c_buf_p) = yytext + yyless_macro_arg; \
			(yy_hold_char) = *(yy_c_buf_p); \
			*(yy_c_buf_p) = '\0'; \
			yyleng = yyless_macro_arg; \
	} while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void) {
	
	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void) {
		return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void) {
		return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void) {
		return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void) {
		return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number ) {
	
	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str ) {
		yyin = _in_str ;
}

void yyset_out (FILE *  _out_str ) {
		yyout = _out_str ;
}

int yyget_debug  (void) {
		return yyflexdebug;
}

void yyset_debug (int  _bdebug ) {
		yyflexdebug = _bdebug ;
}

static int yy_init_globals (void) {
		/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

	(yy_start_stack_ptr) = 0;
	(yy_start_stack_depth) = 0;
	(yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {
	
	/* Pop the buffer stack, destroying each element. */
	while(yy_current_buffer()) {
		yy_delete_buffer( yy_current_buffer()  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	/* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n ) {
		
	int i;
	for ( i = 0; i < n; ++i ) {
		s1[i] = s2[i];
	}
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size ) {
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size ) {
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr ) {
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#line 279 "scanner.l"



